### ISSUE TITLE
IDE features don't work in multi folder projects

### ISSUE THREAD

**Issue by alexfedoseev** [facebook-atom/atom-ide-ui#107]
### Description
IDE features don't work (hyperclick, data tips etc) in [multi folder projects](http://blog.atom.io/2015/04/15/multi-folder-projects.html) when one of the folders is parent of another. When each folder is opened separately or there's no folders overlapping—everything works.

Tested with:

```
ide-flowtype@0.17.4
ide-reason@0.1.3
```

### Expected Behavior
When package looks up root directory of a current file it should pick the first matched root from array of opened folders.

E.g.:

```
ROOT (/)
  |-- client/
      |-- app/
          |-- module.js
CLIENT (/client)
  |-- app/
      |-- module.js
```
In the example above, when `client/app/module.js` is opened, its root should be resolved to `CLIENT (/client)` folder.

### Actual Behavior
Now it's resolved to `ROOT (/)` and IDE features don't work.

### Versions
* Atom: `1.21.1`
* Client OS: `macOS 10.12.6`
* atom-ide-ui: `0.5.3`

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (40) /Users/Alex/.atom/packages
├── advanced-open-file@0.16.7
├── atom-ide-ui@0.5.3
├── autocomplete-modules@1.6.10
├── color-picker@2.2.5
├── cursor-history@0.12.0
├── custom-title@1.0.1
├── file-icons@2.1.13
├── flex-tool-bar@0.12.0
├── git-blame@1.3.1
├── go-plus@5.6.0
├── go-signature-statusbar@1.2.3
├── highlight-selected@0.13.1
├── ide-flowtype@0.17.4
├── ide-reason@0.1.3
├── language-applescript@0.3.0
├── language-babel@2.76.1
├── language-docker@1.1.8
├── language-jade@0.7.2
├── language-nginx@0.8.0
├── language-ocaml@1.9.5
├── language-pug@0.0.21
├── language-reason@0.0.4
├── language-slim@0.6.0
├── language-swift@0.5.0
├── linter@2.2.0 (disabled)
├── linter-docker@0.2.1
├── linter-eslint@8.4.0
├── linter-refmt@0.3.1
├── linter-scss-lint@3.1.1
├── linter-stylelint@4.0.2
├── maximize-panes@0.2.0
├── nice-index@1.0.5
├── nucleus-dark-ui@0.12.3
├── pg-formatter@0.0.1
├── prettier-atom@0.40.0
├── set-syntax@0.4.0
├── todo-show@2.1.0
├── tool-bar@1.1.0
├── vim-mode-plus@1.13.0
└── zentabs@0.8.8
```

**Comment by hansonw** [comment]
Please see https://github.com/flowtype/ide-flowtype/issues/13 - this problem has to be resolved in the language client, sorry!
