### ISSUE TITLE
Multiple lines 

### ISSUE THREAD

**Issue by Ewwe** [facebook-atom/atom-ide-ui#109]
Hi , when i have enabled atom-ui-ide i cant edit or type on multiple lines. I mean when im holding CTRL and then clicking to diferent rows cursor will duplicate and i can type on multiple rows.

### Versions
* Atom: 1.21.2
* Client OS: Windows 10
* atom-ide-ui: 0.53

**Comment by damieng** [comment]
Dupe of https://github.com/facebook-atom/atom-ide-ui/issues/61

**Comment by Ewwe** [comment]
Oh sorry
