### ISSUE TITLE
Hiding status bar message

### ISSUE THREAD

**Issue by niccolomineo** [facebook-atom/atom-ide-ui#115]
Hi,
how do I hide the "PHP (FelixFBecker) started" message in the status bar?

Thanks,
N

**Comment by damieng** [comment]
That's actually caused by ide-php itself and should have been replaced in the latest version with the busy signal indicator.  Please file an issue at https://github.com/atom/ide-php with a screenshot if you still get it in ide-php 0.6.9 or later.
