### ISSUE TITLE
Diagnostics automatic show/hide doesn't work for current file

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#124]
### Description

When the mode for the diagnostics panel is set to `Current File Only` and the current file has no diagnostic messages _but_ other files in the project do, the panel doesn't automatically hide.

### Expected Behavior

"Automatically show and hide diagnostics panel" should respect the "Current File Only" setting and hide itself when the current file has no messages.

### Actual Behavior

"Automatically show and hide diagnostics panel" only counts the _total_ message counts, meaning when other files in the project have messages it stays visible.

### Versions
* Atom: v1.23.0-beta1
* Client OS: Windows 10 x64
* atom-ide-ui: v0.6.0

**Comment by pelmers** [comment]
Thanks for posting the issue, when I added the option I wasn't sure whether to have it respect the file/text filters and decided to wait for feedback to appear.

But after using it for some time I agree that it would be more useful if it shows/hides based on all the diagnostics filters.

**Comment by matthewwithanm** [comment]
@pelmers @captbaritone was talking about this the other day…i don't agree that we should use _all_ the filters. the text filter is definitely something you're likely to pass through no-message states with. the type filter is a bit more of a toss-up (i think @captbaritone and i disagreed about it?), but imo that's more of an ephemeral one too. in other words, i think that only the scope one (file/project) should be taken into account (:

**Comment by Arcanemagus** [comment]
The text filter I would say definitely wouldn't be something to use to determine this.

The type filter is... interesting. Personally I think I'd say it shouldn't be used, but I know there are a lot of people out there that want the ability to only deal with errors and ignore everything else, so they might want that functionality.

**Comment by hansonw** [comment]
Will be fixed in the (upcoming) release.
