### ISSUE TITLE
Disable autocompletion

### ISSUE THREAD

**Issue by ricpelo** [facebook-atom/atom-ide-ui#129]
Hi!

Can I disable autocompletion only for atom-ide-ui suggestions? So autocomplete-plus still works for other packages, but not for this one.

Thanks in advance.

**Comment by damieng** [comment]
Atom IDE UI is not involved in autocompletion.  That is between the ide-* package and Atom.

**Comment by ricpelo** [comment]
Thank you very much and sorry for the noise!

**Comment by WLyKan** [comment]
i have this problem too, it was cause by https://github.com/rwatts3/atom-ide-vue/issues/4
