### ISSUE TITLE
Completely blocks Atom's menu!

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#13]
If the user has enabled the "Auto Hide Menu Bar" option in Atom the normal way of getting it to show is to press the <kbd>Alt</kbd> key, unfortunately it seems `atom-ide-ui` has defined a keybind (`datatip:toggle`) for this, which both does nothing when there is no `datatip` to show, and more importantly blocks the menu from appearing.

For anyone hitting this issue and looking for a workaround:
I managed to get the menu to show by clicking in the `tree-view` area and then hitting <kbd>Alt</kbd>.

**Comment by hansonw** [comment]
@wbinnssmith should we remove this keybind?

**Comment by jonyeezs** [comment]
options to change keybindings should be available for cases such as these.

**Comment by hansonw** [comment]
@jonyeezs To unbind this in the meantime you can always insert this in your `keymap.cson`:

```
'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'alt': 'unset!'
```

**Comment by hansonw** [comment]
Fixed by bbbe3fff8de3b9b86694e7b75b4fee252e22fd8e

**Comment by jonyeezs** [comment]
Yup did that and rebind it to something else

**Comment by umpirsky** [comment]
How can we toggle datatip now? What is the new keybinding?

**Comment by Arcanemagus** [comment]
@umpirsky There currently isn't one, you can add one yourself in your custom keymaps.
