### ISSUE TITLE
Feature request: Option to ignore folders/files from Outline

### ISSUE THREAD

**Issue by rejhgadellaa** [facebook-atom/atom-ide-ui#135]
### Description
Am I correct in the assumption that the IDE package tries to get an outline for the entire project? If so, it would be nice if we had an option to exclude/ignore folders.

For example, I have Atom projects that include both a 'development' and a 'production' folder (where the prod folder contains pre-processed (gulp; minimized, optimized, etc) files). This makes Outline very slow (it seems to not finish processing at all, sometimes).

### Versions
* Atom: 1.23.x
* Client OS: Windows 10
* atom-ide-ui: 0.7.0

**Comment by hansonw** [comment]
This should be managed by the ide- package (or atom-languageclient). Follow https://github.com/atom/atom-languageclient/issues/159 for related discussions (I imagine you've ignored the generated files in Atom.)
