### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir '~/Application Data'

### ISSUE THREAD

**Issue by sguergachi** [facebook-atom/atom-ide-ui#139]
[Enter steps to reproduce:]

1. Opened a file in the user dir on Windows

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'C:\Users\Sammy\Application Data'

```
At C:\Users\Sammy\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:69

Error: EPERM: operation not permitted, scandir 'C:\Users\Sammy\Application Data'
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:17.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
highlight-selected 0.13.1 
ide-html 0.4.1 
ide-typescript 0.7.2 
intentions 1.1.5 
linter 2.2.0 
linter-flow 5.6.1 
linter-ui-default 1.6.10 
minimap-highlight-selected 4.6.1 
prettier-atom 0.43.1 
rainbow-tabs 2.5.1 
sync-settings 0.8.3 
```

**Comment by Arcanemagus** [comment]
This isn't actually an issue with `atom-ide-ui`, Atom is just reusing the `rxjs` module from its directory and thus it thinks that's where this came from. Unfortunately from your stack trace it doesn't seem obvious which of your packages _actually_ triggered this error, I would look towards the `ide-typescript` though, since that's where the `vscode-jsonrpc` was being used from.

**Comment by hansonw** [comment]
Thanks @Arcanemagus! Yup this looks like an `ide-typescript` issue, there have been a number of reports about this particular error message lately.
