### ISSUE TITLE
Flow inline coverage information with underlining

### ISSUE THREAD

**Issue by gregtatum** [facebook-atom/atom-ide-ui#142]
### Description
Nuclide provides inline coverage information for flow coverage. I use this as a core part of my workflow to know that I'm using Flow effectively. It would be really nice if Atom IDE could support this as well. This is a blocker keeping me from switching to Atom IDE from Nuclide.

For example, here `element` has no coverage, and provides a nice hint inline:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1588648/34799280-dd90dee0-f624-11e7-92f9-000fe0113fd0.png">

There is also a nice toggle button and coverage button at the bottom as well:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/1588648/34799352-132e41a0-f625-11e7-8008-fde70a83595d.png">

**Comment by damieng** [comment]
I agree this would be a great feature - not sure which lsp messages we could piggy-back this on or whether we'd need to create or propose extensions.

**Comment by hansonw** [comment]
Yup this can be recreated in a pretty straightforward way with `workspace/executeCommand` - if w register a new command to toggle/untoggle Flow coverage they can be sent back as plain diagnostics (this is what Nuclide does as well, just in a different way).

Let's keep the discussion in https://github.com/flowtype/ide-flowtype/issues/14; I don't promise anything but I can try to implement this if I have some free time. (Or maybe @wbinnssmith, if he has some time).
