### ISSUE TITLE
No way to unselect a message

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#143]
### Description
If you _ever_ click a message, you are permanently stuck with a selected message in your panel until you remove all messages or reload Atom.

### Expected Behavior
Clicking elsewhere in the editor (out of the range of the `diagnostic`), or in a blank area of the panel should deselect the message.

### Actual Behavior
Once a message is selected you can only deselect it by selecting another message.

### Versions
* Atom: v1.24.0-beta3
* Client OS: Windows 10 x64
* atom-ide-ui: v0.7.1

### Additional Details
This is an _exact_ duplicate of #82, in which repeated comments that this has re-appeared have been ignored.

This was an issue in v0.5.0, it was fixed in v0.5.2, and then re-introduced in v0.5.4 ([commit range](https://github.com/facebook-atom/atom-ide-ui/compare/v0.5.3...v0.5.4)).

**Comment by matthewwithanm** [comment]
Sorry, pushing a fix now 😞
