### ISSUE TITLE
Code actions should return focus to the editor

### ISSUE THREAD

**Issue by hansonw** [facebook-atom/atom-ide-ui#147]
After applying a code action via the diagnostic datatip, focus goes back to the document body (since the datatip gets unmounted immediately after the action is applied). We should return focus to the editor, at least.

This would be a simple starting PR. One solution would be to tell Atom to re-focus the current element; this would look like:

```
const activeItem = atom.workspace.getActivePaneItem();
if (activeItem != null && activeItem.element instanceof HTMLElement) {
  activeItem.element.focus();
}
```

And you can inject it here, where the code actions are wrapped for the popup.

https://github.com/facebook-atom/atom-ide-ui/blob/f2d921a9cc4710b440b8ec468fd6eca50d989e53/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsPopup.js#L77-L79

**Comment by tylerFowler** [comment]
Submitted a PR, in my local tests I never observed the suggested fix location being called, it always seemed to be applied at `DiagnosticsCodeActions.js` around line 38. As mentioned in the PR I assume these two code paths are mutually exclusive but I'm not familiar enough with the codebase to be super confident about that.
