### ISSUE TITLE
Hyperclick not working

### ISSUE THREAD

**Issue by RAbraham** [facebook-atom/atom-ide-ui#149]
UPDATED(an hour after initial post):
Hyperclick functionality takes some time to load after I open the file. It seems to work after the `ide-python` comes back with linting errors. I'm guessing after it returns from the python language server.

Is this a ticket I should raise with the `ide-python` or here? Sorry if this is meant for `ide-python` but the code for `ide-python` seems minimal.

### Versions
* Atom: 1.23.3
* Client OS: Mac OS El Capitan( 10.11.6)
* atom-ide-ui: 0.7.1

### Additional Details
* Installed packages (`apm ls --installed`):

Community Packages (8) /Users/rabraham/.atom/packages
├── Hydrogen@2.2.2
├── atom-ide-ui@0.7.1
├── cursor-history@0.12.0
├── ide-python@0.5.0
├── intellij-idea-keymap@0.2.3
├── organized@0.8.1
├── python-tools@0.6.9 (disabled)
└── tool-bar@1.1.4

**Comment by epelc** [comment]
Maybe related? https://github.com/facebook-atom/hyperclick/issues/44

**Comment by wi-ski** [comment]
This issue has been killllllling meeeeee

**Comment by hansonw** [comment]
`ide-python` uses https://github.com/palantir/python-language-server underneath. It wouldn't surprise me that it takes some time to initialize and update the Python language server - you could check the issues list there perhaps.
