### ISSUE TITLE
Disable code completion in comment section

### ISSUE THREAD

**Issue by tylerFowler** [facebook-atom/atom-ide-ui#15]
While writing comments (esp. longer doc comments) I noticed that code completion is on, unnecessarily. Perhaps it could be an option to disable this?

**Comment by hansonw** [comment]
Autocomplete is actually built into Atom already (autocomplete-plus). If you go into the package settings there's a "scopeBlacklist" config that can do exactly what you want :)

**Comment by tylerFowler** [comment]
Ahhh ok, I had assumed the smarter code completion was more custom. Awesome, thanks!

**Comment by hansonw** [comment]
Depending on what kind of suggestions you're getting, this may be something the language server should be doing by default. It may be worth following up on the ide-* repo as well.

**Comment by tylerFowler** [comment]
That was my original thought, though the autocomplete blacklist seemed to work. Ideal scenario I think is to keep word ("normal") autocomplete on in comments but turn off the part that shows the suggestions provided by the language server as you mentioned.

I'll follow up on the specific package, thanks again!
