### ISSUE TITLE
HyperClick not working

### ISSUE THREAD

**Issue by verydanny** [facebook-atom/atom-ide-ui#153]
### Description
CMD + Click doesn't hyperlink. No issues found in the developer console. Tried disabling all packages except atom-ide-ui and only its dependencies.

### Expected Behavior
Should go to definition/file on a hyperlink click.

### Actual Behavior
Nothing at all, developer console doesn't show any errors.

### Versions
* Atom: 1.23.3
* Client OS: High Sierra 10.13.2
* atom-ide-ui: 0.7.2

### Additional Details
```bash
Community Packages (10) /Users/danii/.atom/packages
├── atom-ide-ui@0.7.2
├── atom-material-ui@2.1.1
├── busy-signal@1.4.3
├── ide-flowtype@0.17.6
├── ide-flowtype-coverage@1.9.2 (disabled)
├── intentions@1.1.5
├── language-babel@2.81.1
├── linter@2.0.0
├── linter-eslint@8.4.0
└── material-palenight-syntax@1.5.7
```

**Comment by hansonw** [comment]
Note that at the minimum you need both `atom-ide-ui` and `ide-flowtype` enabled (as `ide-flowtype` actually provides the Hyperclick results). Can you enable LSP debugging by running

```
atom.config.set('core.debugLSP', true)
```

in the developer console to see if definition requests are getting sent through? It's unclear if the problem is with the UI or with the flowtype package.

**Comment by verydanny** [comment]
I fixed it, it was an issue with a global flow conflicting with ide-flowtype.

Thanks :)

**Comment by Rohithzr** [comment]
It's not working for me. pressing cmd doesn't turn anything to hyperlink and cmd+click (MacOS hyperclick) doesn't do anything either.

packages installed
```
ls ~/.atom/packages
README.md    atom-ide-ui  hyperclick   ide-flowtype nuclide      react
```
also tried https://github.com/facebook-atom/hyperclick/issues/20

ran this command too
`atom.config.set('core.debugLSP', true)`

didn't see any relevant errors, except these.
```
Unable to locate git workspace root for /Users/rohithazra/Work/adshopar_backend. Expected if /Users/rohithazra/Work/adshopar_backend is not in a git repository
...

nuclide-watchman-helpers - Error while talking to watchman:  Watchman was not found in PATH....
```
