### ISSUE TITLE
Trigger signature help if trigger character occurs in autocompletion suggestion

### ISSUE THREAD

**Issue by Gert-dev** [facebook-atom/atom-ide-ui#156]
### Description
It is probably a good idea to describe this with a concrete use case.

Language servers have complete freedom as to what they send in autocompletion suggestions and what text edits they can cause. In my case - not a language server, but bear with me - I have autocompletion suggestions for functions and member methods that insert parantheses, i.e.:

```php
<?php

$this->foo // Trigger completion and activate suggestion with text "foobar($0)"
$this->foobar(|); // Completion triggered, cursor is placed between the parantheses
```

The trigger character for signature help in my client is set to trigger on the opening paranthesis `(`. This works when the user manually types the `(`, but it does not if he types it implicitly by triggering an autocompletion suggestion, even though the character in front of the cursor is the trigger character.

I am convinced that showing signature help here immediately is beneficial to the user and that omitting the parantheses from the suggestion would be detrimental to the user, but is it possible for atom-ide-ui to trigger signature help by checking the trigger characters after autocompletion insertions as well?

I admit this may be an uncommon use case. I'm aware there is also a `command` that can be shipped with autocompletion suggestions, but nothing in the language server specification suggests that it is in fact tied to any of the other official request types. If it were, I could, in theory, send a `trigger signature help` command along with the appropriate autocompletion suggestions, which would then be executed after the completion by the language client.

### Expected Behavior
Signature help triggers even if trigger character is implicitly inserted via autocompletion.

### Actual Behavior
Signature help is not triggered after autocompletion, even if the trigger character is in front of the cursor after the completion, but only when the user manually inserts it.

### Versions
* Atom: 1.23.3
* Client OS: Linux 64-bit
* atom-ide-ui: 0.7.2

**Comment by hansonw** [comment]
No this totally makes sense - I'll look into why this isn't working. I
probably only allowed single character insertions at the moment.

I believe "over typing" (overwriting an open paren, for example) also
doesn't work but should work.

**Comment by hansonw** [comment]
Forgot to update this - this is in v0.11.1 (https://github.com/facebook-atom/atom-ide-ui/commit/b2539322f563ab2a6122e2b2998a71d1ef9c274b#diff-563149fc08a83b5076cf33a3a35a93bd).
