### ISSUE TITLE
Prioritizing user snippets in autocomplete suggestions

### ISSUE THREAD

**Issue by saadq** [facebook-atom/atom-ide-ui#157]
### Description
Currently, using user code snippets isn't reliable with `ide-*` packages due to the fact that they aren't placed at the top. In my case, I have a `cl` snippet which should expand to `console.log()`, however it is placed as the second suggestion, so I can't just do <kbd>cl</kbd>+<kbd>tab</kbd>.

![screen shot 2018-01-30 at 11 55 35 am](https://user-images.githubusercontent.com/5678694/35579695-3baf3e78-05b5-11e8-888c-377bd50fce6d.png)

Ideally, this wouldn't occur or there could possibly be a boolean setting in `atom-ide-ui` for keeping user snippets at the top.

I noticed this problem with `ide-flowtype`, but [an issue](https://github.com/atom/autocomplete-plus/issues/946#issuecomment-361643991) in the `autocomplete-plus` repo seems to suggest that this happened with `ide-cquery` as well, which is why I thought it would be best to open this issue here.

### Expected Behavior
User snippets should be placed at the top of autocomplete suggestions.

### Actual Behavior
User snippets are not placed at the top of autocomplete suggestions.

### Versions
* Atom: 1.23.3
* Client OS: macOS High Sierra 10.13.3
* atom-ide-ui: 0.7.2

### Additional Details
* Installed packages (`apm ls --installed`): [GitHub Gist](https://gist.github.com/anonymous/0ad0667e55a21afd721654a29e6f4cdd)

**Comment by hansonw** [comment]
https://github.com/atom/atom-languageclient is responsible for registering autocomplete, actually (atom-ide-ui does not provide any autocomplete functionality). But ultimately I think it'll be up to the `ide-*` packages to decide what the right priority is.

`ide-flowtype` overrides the autocomplete priority here: https://github.com/flowtype/ide-flowtype/blob/master/lib/main.js#L122

So maybe you could make a PR there to make that more configurable. I think another solution would be to add a config to the snippets autocomplete provider to increase the priority of user snippets (it doesn't seem like that exists yet).
