### ISSUE TITLE
Text editor keeps freezing after latest update

### ISSUE THREAD

**Issue by martezconner** [facebook-atom/atom-ide-ui#161]
Atom version: 1.23.3
Atom-IDE-UI ver: 0.8.1

After updating the application freezes after 20-30 seconds and I have to force close

**Comment by drmathochist** [comment]
Is this still happening after the usual restarting and clearing caches?

**Comment by Arcanemagus** [comment]
What `ide-*`/`linter-*` providers do you have installed? What do you have open when it freezes?

**Comment by martezconner** [comment]
@Arcanemagus I have ide-typescript and that is it. I disabled one linter I dont know the repo author exactly. Right now I am going to reinstall Atom and see if that helps

**Comment by martezconner** [comment]
@drmathochist After the application freezes my windows system asks me if I'd like to force close I click yes and reopen but the same issue arises. Ill try clearing caches and see if that helps

**Comment by martezconner** [comment]
@Arcanemagus @drmathochist  so it looks like it works after running the [atom --clear-window-state] cmd from my powershell terminal
