### ISSUE TITLE
Useless interfering hotkeys "Nuclide" menu

### ISSUE THREAD

**Issue by zorn-v** [facebook-atom/atom-ide-ui#162]
### Description
After last update that menu appers with one submenu "Console -> Clear".
The stuff is that when you press ALT+SHIFT it falls and prevents hotkeys with this combination.

### Versions
* Atom: 1.23.1
* Client OS: Kubuntu 17.10
* atom-ide-ui: 0.8.1

**Comment by bgarrant** [comment]
Why is Nuclide in the menu?

**Comment by damieng** [comment]
Nuclide is in the menu because of this; https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-console/menus/console.json#L13

It looks like this menu option should probably be removed or made contextual on the console control itself.

**Comment by bgarrant** [comment]
It should probably be removed I agree. I don’t see the need for it.

**Comment by hansonw** [comment]
Sorry, this just slipped through as we migrated the console to live in
atom-ide-ui. We'll remove it shortly!

**Comment by bgarrant** [comment]
Thanks so much.

**Comment by matthewwithanm** [comment]
this should be fixed in the next release! thanks again for bringing it to our attention!

**Comment by wbinnssmith** [comment]
Just pushed a release that resolves this! Thanks for your help everyone!
