### ISSUE TITLE
Documentation for Console

### ISSUE THREAD

**Issue by feakuru** [facebook-atom/atom-ide-ui#167]
### Description
So I see that atom-ide-ui has some built-in atom-ide-console. I couldn't find the docs for it, what it is, how to use this, whatsoever. If I am mistaken, please be so kind as to point me to the documentation. Because all I currently have is a panel with a promising "Showing: 0 sources" info message.

### Expected Behavior
Console functionality (whatever that is. A terminal?..)

### Actual Behavior
"Showing: 0 sources" 

### Versions
* Atom: 1.23.3
* Client OS: XUbuntu 17.10
* atom-ide-ui: 0.8.1

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (25) /home/feakuru/.atom/packages
├── atom-django@0.3.2
├── atom-ide-ui@0.8.1
├── atom-material-syntax@1.0.8
├── atom-material-syntax-dark@1.0.0
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.2
├── autocomplete-python@1.10.5 (disabled)
├── busy-signal@1.4.3
├── clojure-indent@0.4.0
├── django-templates@0.5.0
├── gl-light-syntax@3.0.0
├── highlight-selected@0.13.1 (disabled)
├── ide-python@0.8.0
├── intentions@1.1.5
├── minimap@4.29.7
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1 (disabled)
├── minimap-selection@4.5.0
├── platformio-ide-terminal@2.8.0
├── pretty-json@1.6.4
├── proto-repl@1.4.22
├── python-indent@1.1.4
└── python-tools@0.6.9
```

**Comment by laughedelic** [comment]
I'm also waiting for the docs and support in atom-languageclient.

> whatever that is. A terminal?

It's more about logging (`window/logMessage`) and extendable REPL functionality to interact with  the language server. 

See also https://github.com/atom/atom-languageclient/issues/4#issuecomment-290786384

**Comment by feakuru** [comment]
@laughedelic wow, that'd be cool. @hansonw, @damieng care to comment on this?

**Comment by hansonw** [comment]
Out on vacation but @matthewwithanm might be able to put up something soon!

On Feb 16, 2018 2:00 PM, "Dmitry Orlov" <notifications@github.com> wrote:

@laughedelic <https://github.com/laughedelic> wow, that'd be cool. @hansonw
<https://github.com/hansonw>, @damieng <https://github.com/damieng> care to
comment on this?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/facebook-atom/atom-ide-ui/issues/167#issuecomment-366229230>,
or mute the thread

**Comment by feakuru** [comment]
@hansonw have a nice vacation ;)

**Comment by matthewwithanm** [comment]
hey all! i'm about to push some docs for this. right now, it's just gonna be documentation around the very basic features as we'd like to update the APIs for some of the more advanced (REPL) stuff.
