### ISSUE TITLE
"No Outline Available: There is Likely an Error with the Language Package"

### ISSUE THREAD

**Issue by JosephTLyons** [facebook-atom/atom-ide-ui#177]
### Description
"No Outline Available: There is Likely an Error with the Language Package," is the message I get with every language that I have ide-language packages for.  C#, HTML, Python,.. etc.  I haven't been able to use any of the IDE features introduce by installing atom-ide-ui+a language package.  Diagnostics, advanced completion, etc.  There is no sign of anything working.

### Expected Behavior
The feature set to work as described.

### Actual Behavior
Same as description.

### Versions
* Atom: 1.24.0
* Client OS: macOS 10.13.3
* atom-ide-ui: 0.9.2

**Comment by hansonw** [comment]
If you open Atom's console (cmd-opt-i), do any uncaught exceptions or rejections appear?

**Comment by hansonw** [comment]
Given that autocompletion also isn't working for you, this seems like a deeper problem - `atom-ide-ui` is not responsible for providing autocompletion results. Only the `ide-` language packages are (via `atom-languageclient`.)

**Comment by JosephTLyons** [comment]
I have the basic autocompletions that existed before installing atom-ide-ui, but nothing new on top of that (to my knowledge at least).  

Here's a screenshot of the console after freshly opening Atom and running the command to show the outline of a sample HTML doc and the `ide-html` package

![screen shot 2018-03-01 at 3 03 44 pm](https://user-images.githubusercontent.com/19867440/36866985-d44ac67a-1d61-11e8-9213-e09a3fdf2be6.png)

**Comment by damieng** [comment]
Hi @JosephTLyons can you try turning on debugging and see what messages you get?

`atom.config.set('core.debugLSP', true);`

and then restart Atom.  You should see more detail then in the dev tools window.    I'm going to close the issue here as it's not atom-ide-ui going wrong here - it's either ide-html or atom-languageclient or atom but we may as well continue the discussion here.

**Comment by JosephTLyons** [comment]
Made that boolean for debug true, closed Atom and reopened, then ran the outline command.  I don't see very many new details however.  And just to reiterate, I have this issue with all idi-language packages, not just HTML.  I just used HTML for this specific example, but the same happens in IDE-Python, IDE-CSharp, etc.

![screen shot 2018-03-01 at 5 26 37 pm](https://user-images.githubusercontent.com/19867440/36873229-da1387a4-1d75-11e8-858b-2cfb16c4c630.png)

**Comment by damieng** [comment]
Ah, do you have tree-sitter experimental support enabled?

**Comment by JosephTLyons** [comment]
Not that I'm aware of.  I'm on Atom 1.24.0 and that new tree-sitter isn't included until Atom 1.25.0 (beta) to my knowledge.  I double-checked and there is no such setting on my end in 1.24.0

**Comment by damieng** [comment]
Can you try pressing ctrl-; in the html editor and paste here a screenshot of the 'scopes at cursor' that comes up?

**Comment by JosephTLyons** [comment]
Hmmm, pressing `control` + ` ;` while my cursor is in the `HTML` doc does nothing on my end, maybe I'm doing something incorrectly?  I'm really wanting to help resolve this, because there is a group of us that ran into this same issue.

**Comment by hansonw** [comment]
On Mac OS I believe it's cmd-opt-P.

**Comment by skylize** [comment]
OS agnostic. Open the file-in-question. While that tab is active, open dev tools, and paste this in the console.
```javascript
atom.workspace.getActiveTextEditor().getLastCursor().getScopeDescriptor().getScopesArray()
```

**Comment by JosephTLyons** [comment]
Thanks, here it is!

<img width="477" alt="screen shot 2018-03-01 at 8 42 24 pm" src="https://user-images.githubusercontent.com/19867440/36879314-1808617c-1d91-11e8-86ed-818e2a5c300e.png">

**Comment by JosephTLyons** [comment]
Would anyone else have any helpful tips?  Sort of at a lose for what to try next or if it will have to a code fix down the line.

**Comment by damieng** [comment]
I'm at a loss to explain why it isn't working on your machine.

**Comment by JosephTLyons** [comment]
@damieng , that's ok.  I appreciate you trying to help.  I will just keep all aspects of Atom IDE disabled and check into it whenever an update comes up.  Thanks again.

**Comment by JosephTLyons** [comment]
Interesting, I disabled and re-enabled the atom-ide-ui package and received a handful of a errors:

<img width="461" alt="screen shot 2018-03-05 at 3 42 05 am" src="https://user-images.githubusercontent.com/19867440/36965307-47aaf80c-2027-11e8-803e-3e54c4f0add2.png">
<img width="464" alt="screen shot 2018-03-05 at 3 42 12 am" src="https://user-images.githubusercontent.com/19867440/36965316-4d3a6780-2027-11e8-9082-3cec8dd23271.png">

**Comment by chibicode** [comment]
@damieng 

> Ah, do you have tree-sitter experimental support enabled? (https://github.com/facebook-atom/atom-ide-ui/issues/177#issuecomment-369755762)

Just curious, why would enabling `tree-sitter` cause a problem here?

**Comment by chibicode** [comment]
Ah, it seems that the scope changes with `tree-sitter`.

https://github.com/AtomLinter/linter-eslint/pull/1115

**Comment by damieng** [comment]
Yes, the scope names change with tree-sitter and packages need to update. Looks like the AtomLinter update should be out soon.

**Comment by JosephTLyons** [comment]
I just updated to the newest Atom with tree-sitter, but It’s been turned off the entire time.

**Comment by JosephTLyons** [comment]
As an update, IDE is working for me more now than before. Before, nothing worked in any languages. Now, ide-rust works perfectly (diagnostics and outline view and such) and ide-csharp seems to be catching syntax errors and such, still no outline view, but progress it seems.
