### ISSUE TITLE
Outline view filter not working since 0.9.2

### ISSUE THREAD

**Issue by fabianbuechler** [facebook-atom/atom-ide-ui#178]
### Description
Outline filter does not filter anymore since upgrading to 0.9.2.

### Expected Behavior
When entering a search term in the "Filter" field, the symbols displayed in the outline view should be filtered.

### Actual Behavior
Nothing is being filtered. Hitting Enter only jumps to the first matching result.

### Versions
* Atom: 1.23.3
* Client OS: Ubuntu 17.10
* atom-ide-ui: 0.9.2

### Additional Details

* MagicPython@1.0.12
* atom-django@0.3.2 (disabled)
* atom-ide-ui@0.9.2
* autumn-highlighter-syntax@1.13.0
* blame@1.0.1
* busy-signal@1.4.3
* change-case@0.6.5
* column-select@1.0.1
* django-templates@0.5.0
* docker@0.8.0 (disabled)
* file-types@0.5.5
* git-plus@7.10.0
* hey-pane@1.1.0
* ide-html@0.4.2
* ide-python@0.8.1
* ide-typescript@0.7.5
* intentions@1.1.5
* language-docker@1.1.8
* language-fish-shell@1.1.0
* language-ini@1.19.0
* language-jenkinsfile@0.1.1
* language-nginx@0.8.0
* language-restructuredtext@1.1.0
* language-robot-framework@2.2.0
* language-svg@0.9.2
* last-cursor-position@0.9.2
* markdown-pdf@2.1.0
* meld-diff@0.2.0
* oceanic-next@1.0.0
* pretty-json@1.6.4
* project-manager@3.3.5
* sort-lines@0.18.0
* split-diff@1.5.2
* symbols-view-plus@0.117.0-plus.1
* todo-show@2.2.0
* toggle-quotes@1.1.0
* xml-formatter@0.11.0

**Comment by hansonw** [comment]
Fixed in 6ae0d6ea80d72ae9bce4c23ef6b96e8d00d35307, will be released shortly.

**Comment by fabianbuechler** [comment]
@hansonw, thank's a lot for fixing that!
