### ISSUE TITLE
Use atom-ide-busy-signal while waiting for Linter V1 providers

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#18]
### Description
It appears that the `atom-ide-busy-signal` feature isn't initializing for me, at least I can't figure out how to get it to show up.

### Expected Behavior

There should be something similar to this from the README showing:
![image](https://user-images.githubusercontent.com/427137/30389596-22761658-9868-11e7-91d0-5c88ebd3ea77.png)

### Actual Behavior
No busy signal appears to be active:
![image](https://user-images.githubusercontent.com/427137/30389568-0e825d50-9868-11e7-872d-5d59ec2e9e84.png)

### Versions
* Atom: 1.21.0-beta0
* Client OS: Windows 10 Enterprise x64

### Additional Details
At first I was trying with `linter`, `linter-ui-default`, and `busy-signal` active, but disabling all those packages (and restarting Atom!) doesn't appear to have gotten this to show up.

**Comment by damieng** [comment]
It's a service you have to specifically implement and unfortunately none of the language servers have any concept of busy as it isn't in the spec.

I was considering wiring it up for startup and shutdown in atom-languageclient so everybody would get it almost automatically (they'd just need to add the relevant service to their package.json)

**Comment by Arcanemagus** [comment]
What about the linter provider translations? It should be pretty simple to wire it up for those.

**Comment by hansonw** [comment]
Yeah this makes a lot of sense to do
