### ISSUE TITLE
Outline View has no icons

### ISSUE THREAD

**Issue by WLLR9505** [facebook-atom/atom-ide-ui#181]
### Description
recently I upgraded the atom-ide to 0.9.2 and realized that no outline view icon was displayed, I tried to reinstall the package and languages ide that I use but did not solve the problem, I tried to reinstall the atom and still did not get a solution.

### Expected Behavior
![image](https://user-images.githubusercontent.com/22595227/36937183-63759bb2-1f07-11e8-96d5-14a48099882c.png)
*web print, I do not have screenshot before the problem*

### Actual Behavior
![image](https://user-images.githubusercontent.com/22595227/36937189-7cfb7f5c-1f07-11e8-9dc7-b84989327b46.png)
*my print*

### Versions
* Atom: 1.24
* Client OS: Windows 10
* atom-ide-ui: 0.9.2

### Additional Details
*I use this packages:*
atom-beautify 0.32
atom-browser 0.68
atom-clock 0.1.16
file-icons 2.1.17
highlight-selected 0.13.1
ide-css 0.2
ide-html 0.4.2
ide-typescript 0.7.5
minimap 4.29.8
minimap-bookmarks 0.4.2
minimap-cursorline 0.4.2
minimap-find-and-replace 4.5.2
minimap-git-diff 4.3.1
minimap-highlight-selected 4.6.1
minimap-linter 2.1.3
minimap-selection 4.5
terminal-tab 0.5.4

**Comment by laughedelic** [comment]
This is already fixed in https://github.com/facebook-atom/atom-ide-ui/pull/179

**Comment by hansonw** [comment]
Duped. I'll make a new release now.

**Comment by WLLR9505** [comment]
Thank you! 🙂
