### ISSUE TITLE
Freshly installed on Windows, nothing seems to be enabled or working

### ISSUE THREAD

**Issue by ryancole** [facebook-atom/atom-ide-ui#187]
### Description

Hi folks,

I've just installed `atom-ide-ui` along with `ide-typescript`, on Windows 10. Nothing seems to change, visually, in regards to the editor. I don't notice any difference. The only thing I see, that seems to be different than stock atom, is the auto-complete suggestions for my JavaScript.

Things that don't appear to be enabled or working are ...

- file icons
- format on save (I enabled it, but doesn't seem to do anything)
- no diagnostics window or anything
- no different syntax highlighting
- no eslint integration

Based on the website and repo, it looks like these are things that should be added by this package?

### Expected Behavior

I was expecting format on save to work, etc.

### Actual Behavior

None of the packages seem to be enabled or working. The only thing I do notice is the auto-complete suggestions for my JS code.

### Versions

* Atom: 1.25.0
* Client OS: Windows 10 64-bit

### Additional Details

```
PS C:\Users\rcole> apm ls --installed
Community Packages (2) C:\Users\rcole\.atom\packages
├── atom-ide-ui@0.9.4
└── ide-typescript@0.7.6
```

![untitled](https://user-images.githubusercontent.com/484801/37624583-a461ddfc-2b96-11e8-8fb4-b7b08b56c2a7.png)

**Comment by hansonw** [comment]
Looks like atom-ide-ui's features are working (note the diagnostics indicators in the bottom-left; cause some syntax errors and hopefully it'll light up!)

1) For file icons, you want https://atom.io/packages/file-icons.
2) ide-typescript currently does not come with a formatter - try https://atom.io/packages/prettier-atom.
3) diagnostics window must be toggled by clicking the icons at the bottom left of your status bar.
4) Syntax highlighting is already provided by Atom :) We don't affect it in any way.
5) ide-typescript also does not come with ESlint. You'll want https://atom.io/packages/linter-eslint

@damieng I wonder if there should be some kind of quick-start guide for Typescript + Atom?

**Comment by ryancole** [comment]
@hansonw OK. Thanks for the info. That makes a bit more sense, now. I do see the hover information, when I hover over functions, variables, etc. So things are definitely working.

What does the code formatting, mentioned in the readme and elsewhere, do? It doesn't seem to do anything.

For JavaScript, if there's no eslint integration, what is going to show up down in the bottom left?

Do these various features expect an underlying formatter and linter to be provided or do they do something by themselves?

**Comment by hansonw** [comment]
1) code formatting relies on having a language server that provides it... For example I think https://atom.io/packages/ide-python provides formatting for Python files. The typescript server just doesn't happen to support it right now. 

2) ESlint is only responsible for lints. TypeScript has a whole extra layer of errors and warnings, ranging from syntax errors to 'compiler errors' (type mismatches, function mismatches, etc.)

In general `atom-ide-ui` provides no functionality directly - you need some kind of provider package (ide-typescript, ide-python) to provide the actual backend.

ide-typescript is very explicit about which features it provides: https://github.com/atom/ide-typescript#features. For anything not covered, you'll have to look elsewhere.

**Comment by ryancole** [comment]
Thanks! That really clears things up. So it's better to look at features of the `ide-*` packages more directly. That typescript one definitely seems to reflect what I see in my editor now.

Have a good evening!
