### ISSUE TITLE
Uncaught TypeError: (0 , (_textEditor || _load_textEditor(...)).getNonWordCharacters) is not a fu...

### ISSUE THREAD

**Issue by uufish** [facebook-atom/atom-ide-ui#188]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.4

### Stack Trace

Uncaught TypeError: (0 , (_textEditor || _load_textEditor(...)).getNonWordCharacters) is not a function

```
At /Users/xxx/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js:38

TypeError: (0 , (_textEditor || _load_textEditor(...)).getNonWordCharacters) is not a function
    at wordAtPosition (/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js:38:87)
    at HyperclickForTextEditor._onMouseMove (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:185:64)
```

### Commands

```
     -0:30.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
```

**Comment by hansonw** [comment]
Please see https://github.com/facebook-atom/atom-ide-ui/issues/64. You may need to clear Atom's compile cache (sometimes just restarting it will do).
