### ISSUE TITLE
Support for more of the linter UI features

### ISSUE THREAD

**Issue by 1951FDG** [facebook-atom/atom-ide-ui#189]
### Description
https://atom.io/packages/linter-ui-default supports some features which atom-ide-ui doesn't:

Decorate on treeview
Show Tooltip
Show Decorations

![screen shot 2018-03-26 at 13 46 59](https://user-images.githubusercontent.com/220168/37904626-b088fbb8-30fc-11e8-8aa3-51b9098d92c3.png)
![screen shot 2018-03-26 at 13 46 40](https://user-images.githubusercontent.com/220168/37904627-b0a3fb3e-30fc-11e8-997b-3ad713ee3f8e.png)
![screen shot 2018-03-26 at 13 46 05](https://user-images.githubusercontent.com/220168/37904629-b0c1cb96-30fc-11e8-8b46-8cf13f73a508.png)

I would be nice to have support for these features as well, since enabling both Diagnostics in atom-ide-ui and enabling https://atom.io/packages/linter, is not optimal

Maybe also, a neat feature that linter can optionally provide, is to lint while on preview, without having to click in editor, for the linting to commence, this feature could be optional, disabled by default for example.

**Update**, I removed the linter packages, all of them including linter, and ignored the prompt to install the linter dependancy for a linter plugin, atom-ide-ui already supports Show Tooltip and Show Decorations apparently (but no settings to toggle), so the only feature missing from linter package is 'Decorate on treeview'

**Comment by captbaritone** [comment]
Agreed! This would be great to have. I don't know of anyone who is currently working on this, but we would gladly accept a pull request. Thanks!

**Comment by Arcanemagus** [comment]
> Update, I removed the linter packages, all of them including linter, and ignored the prompt to install the linter dependancy for a linter plugin

As a note, unfortunately right now you'll keep getting prompted every time that provider activates (Atom restarts). The simplest thing is to leave `linter` installed but disabled.
