### ISSUE TITLE
No Diagnostics panel

### ISSUE THREAD

**Issue by The-Bob** [facebook-atom/atom-ide-ui#190]
### Description
I have no diagnostics panel.  Doesn't show a errors/warnings in bottom bar and alt-shift-d does nothing.

### Versions
* Atom: 1.25.0
* Client OS: Fedora 27
* atom-ide-ui: 0.9.4

**Comment by hansonw** [comment]
Can you check your `~/.atom/config.cson` to see if you have `atom-ide-diagnostics-ui` disabled? If you also have `linter` installed we'll make you pick one of the two, you might've picked linter instead.

**Comment by The-Bob** [comment]
Yep that's it, I think I installed linter a while ago and forgot to turn diagnostics back on.  Thanks!
