### ISSUE TITLE
Feature Request: Terminal

### ISSUE THREAD

**Issue by Superdanby** [facebook-atom/atom-ide-ui#197]
There are various terminal packages out there. But they don't really blend in well with atom-ide-ui. Adding a built-in terminal in this package may benefit millions of people using Atom.

**Comment by pelmers** [comment]
This feature is coming soon, stay tuned!

**Comment by pelmers** [comment]
it's here!! https://github.com/facebook-atom/atom-ide-ui/commit/967100cb0b501488e216c800a5242d3b2a8d8ed3
