### ISSUE TITLE
No errors/warnings displayed in Diagnostics

### ISSUE THREAD

**Issue by EnoraNedelec** [facebook-atom/atom-ide-ui#198]
### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.
* If your issue is language-specific, please file an issue against
  the "ide-" language package you're using instead.

I have installed atom-ide-ui and 4 language packages (html, css, json and python - I have the required packages to make ide-python work). 

### Description
I don't see any errors/warning on the diagnostics pane, even if my files are full or errors
I have installed/uninstalled the atom-ide-ui and 2 language packages many times / restart via atom  and via apm. 
I also had installed linter (+ the required packages) but as it wasn't showing the errors, I uninstalled it. 

There is no message in Dev tool  with atom.config.set('core.debugLSP', true)

### Versions
* Atom: 1.25.0 64
* Client OS: windows 10 64
* atom-ide-ui: 0.9.4

### Additional Details
* Installed packages (`apm ls --installed`):
├── ask-stack@2.2.0 (disabled)
├── atom-beautify@0.32.2
├── atom-css-comb@3.3.1
├── atom-html-preview@0.2.5
├── atom-ide-ui@0.9.4
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── copy-path@0.5.1
├── Delete-Whitelines@0.6.3
├── emmet@2.4.3
├── file-icons@2.1.18 (disabled)
├── fonts@3.0.3
├── highlight-selected@0.13.1
├── html-special-character-replacer@1.1.0
├── hyperlink-hyperclick@2.0.0
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-python@0.9.2
├── intentions@1.1.5
├── language-AHK@0.0.2
├── language-batch@0.4.0
├── linter@2.2.0 (disabled)
├── linter-htmlhint@1.4.0 (disabled)
├── linter-python@3.1.2 (disabled)
├── linter-python-pep8@0.2.0 (disabled)
├── linter-ui-default@1.7.1 (disabled)
├── minimap@4.29.8
├── minimap-highlight-selected@4.6.1
├── multirow-tabs@0.3.3
├── pigments@0.40.2 (disabled)
├── project-manager@3.3.5
├── script@3.17.3
├── simple-drag-drop-text@0.4.0
├── Sublime-Style-Column-Selection@1.7.4
├── sync-settings@0.8.6
└── teletype@0.11.0 (disabled)

**Comment by Arcanemagus** [comment]
`linter` and `atom-ide-ui` use the same protocol for handling diagnostics, so if one wasn't working the other wouldn't be showing anything either.

You mention `ide-python`, but your list of packages only shows one package that looks like it _could_ be a diagnostics provider: `ide-html`, unfortunately from the description of the [vscode-html-languageserver](https://github.com/vscode-langservers/vscode-html-languageserver-bin) that it is calling out to, it seems this is a rare one that doesn't offer any diagnostics. So it seems that you don't currently have anything installed that would provide diagnostics to show.

What diagnostics were you expecting to show?

**Comment by EnoraNedelec** [comment]
Sorry I didn't paste the correct list of installed packages. I have updated the list in my first post. 

Well I expect to see the warnings at the bottom left lightin up and to see some errors reported in the diagnotics pan. As you can see [here](https://imgur.com/a/QQ9HI), I don't have any errors reported, even though my code if full of errors. 

I tried to modify the file and then save it but still the diagnostics pan remains empty.

**Comment by Arcanemagus** [comment]
If you still have `linter` installed, can you enable it and run `Linter: Debug` from the Command Palette? That will show a list of matching diagnostic providers.

**Comment by EnoraNedelec** [comment]
Here is the `Linter: Debug` when atom-ide is enable 

```
Platform: win32
Atom Version: 1.25.1
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
Indie Linter Providers: 
  - Code Actions
  - CSS/LESS/SCSS (VSCODE-CSS-LANG-SERVER)
  - HTML (VSCODE-HTML-LANG-SERVER)
  - JSON (VSCode)
  - Python (pyls)
UI Providers: 
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.python

```

If I disable atom-ide (and the related packages) and enable linter and its packages, the only line that changes is : 
```
UI Providers: 
  - Linter
```

**Comment by mwilliammyers** [comment]
I had the exact same issue. I downgraded to `v0.9.2` and it worked (`v0.9.3` and `v0.9.4` did not work).

**Comment by wanderley** [comment]
It has been a while that this issue was opened, and we already had many releases after that. I am closing this issue but feel free to open a new one if the problem persist in the most recent release.
