### ISSUE TITLE
atom-ide-ui Code formatting is not supported

### ISSUE THREAD

**Issue by linjialiang** [facebook-atom/atom-ide-ui#203]
### Before Submitting

* atom-ide-ui Code formatting is not supported
  - php
  - javascript
* atom-ide-ui Code completion is not supported
  - php
  - javascript

### Versions
* Atom: 1.25.1
* Client OS: windows 10
* atom-ide-ui: 0.9.4

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-ide-ui@0.9.4
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-php@0.7.14
└── ide-typescript@0.7.6

**Comment by hansonw** [comment]
Unfortunately it looks like neither the `ide-php` nor `ide-typescript` packages implement code formatting, as the PHP and Typescript language servers don't support it (try `atom-beautifier` or similar).

As for code completion, that's provided by `autocomplete-plus` and has nothing to do with `atom-ide-ui` - so you'll have to debug a bit further. Sorry!
