### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by Dweessies** [facebook-atom/atom-ide-ui#208]
### Description
Install failed.  Previously I had tried to update, but that ALWAYS fails.  My normal workaround for this was to uninstall the old version and then install the new one.  That didn't work this time.  The install fails with the following message.

Installing “atom-ide-ui@0.10.1” failed.Hide output…
C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr
`-- (empty)

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\package.json'
npm WARN apm-install-dir-118317-25468-b2d91w.mb2sa46lxr No description
npm WARN apm-install-dir-118317-25468-b2d91w.mb2sa46lxr No repository field.
npm WARN apm-install-dir-118317-25468-b2d91w.mb2sa46lxr No README data
npm WARN apm-install-dir-118317-25468-b2d91w.mb2sa46lxr No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\WEESD002\\AppData\\Local\\atom\\app-1.26.0-beta0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\WEESD002\\AppData\\Local\\atom\\app-1.26.0-beta0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\WEESD002\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\WEESD002\\.atom\\.apmrc" "install" "C:\\Users\\WEESD002\\AppData\\Local\\Temp\\d-118317-25468-1calya6.v8ultprpb9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\.staging\core-js-5bab77f4
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\.staging\core-js-5bab77f4' -> 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\atom-ide-ui\node_modules\core-js'
npm ERR!     at destStatted (C:\Users\WEESD002\AppData\Local\atom\app-1.26.0-beta0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\WEESD002\AppData\Local\atom\app-1.26.0-beta0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\.staging\core-js-5bab77f4' -> 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\atom-ide-ui\node_modules\core-js'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\.staging\core-js-5bab77f4' -> 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\atom-ide-ui\node_modules\core-js'
npm ERR!     at destStatted (C:\Users\WEESD002\AppData\Local\atom\app-1.26.0-beta0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\WEESD002\AppData\Local\atom\app-1.26.0-beta0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\.staging\core-js-5bab77f4' -> 'C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\node_modules\atom-ide-ui\node_modules\core-js'
npm ERR!     at Error (native) parent: 'atom-ide-ui' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\WEESD002\AppData\Local\Temp\apm-install-dir-118317-25468-b2d91w.mb2sa46lxr\npm-debug.log
npm ERR! code 1

### Expected Behavior
I'd like to think that the install should work, but it's referencing a \Temp\ folder, so something appears to have gone very wrong.

### Actual Behavior
I get that message above, and nothing else.

### Versions
* Atom: 1.26.0-beta0 x64
* Client OS: Windows 7
* atom-ide-ui:  Trying to install 0.10.1 (the current one)

### Additional Details

[apm.docx](https://github.com/facebook-atom/atom-ide-ui/files/1921104/apm.docx)

**Comment by hansonw** [comment]
Looks like https://github.com/atom/atom/issues/14913 (unfortunately no resolution yet).
This doesn't seem specific to atom-ide-ui.
