### ISSUE TITLE
Debugger: Breakpoints do not work reliably with source-mapped files

### ISSUE THREAD

**Issue by robertrossmann** [facebook-atom/atom-ide-ui#209]
### Description

When I attempt to debug a project with source maps using `atom-ide-debugger-node`, I get the following error in the IDE console and the debugger does not stop on any breakpoint I set in any of the original source files:

```
Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Column must be greater than or equal to 0, got -1
  at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/source-map/lib/source-map-consumer.js:543:13)
  at BasicSourceMapConsumer.SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/source-map/lib/source-map-consumer.js:748:22)
  at SourceMap.generatedPositionFor (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:169:34)
  at SourceMaps.mapToGenerated (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:36:18)
  at args.breakpoints.forEach.bp (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:77:53)
  at Array.forEach (<anonymous>)
  at EagerSourceMapTransformer.setBreakpoints (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:75:34)
  at validateBreakpointsPath.then (/Users/robert/.atom/packages/atom-ide-debugger-node/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:831:40)
  at <anonymous>
  at process._tickCallback (int[...]
```

#### To replicate the issue:

- Compile _index.mjs_ to _index.js_ with either inline or external source map (or both) into the same directory (all files are in the same path) using `babel . --source-maps both --extensions .mjs --out-dir .`
- Open _index.mjs_ and set a breakpoint somewhere
- Observe that the breakpoint is marked as **unresolved** even though source map for this file exists
- Start a test suite and attach the debugger to this running process (the suite is started with `--inspect --inspect-brk` flags)
- Debugger attaches to this process successfully and waits for me to press the _Continue_ button
- When I press that button, the above error is shown in IDE Console and the test suite never stops on the breakpoint

Alternative and faster way to try locally:

```sh
git clone https://github.com/strvcom/atlas.js
cd atlas.js
make
atom .
make test-debug
```

- From the tree view, open _packages/atlas/src/atlas.mjs_ and set a breakpoint in any of the class' functions
- Open Debugger UI and attach to a running inspector at port 9229
- Pres _Continue_
- Observe error

#### Circumventing this error

I have also found a way to make breakpoints work just fine in the source files (_.mjs_):

- Open the compiled (_.js_) file and set a breakpoint there
- Let the Debugger hit that breakpoint
- The original (_.mjs_) file opens in the editor
- Now you can freely set a breakpoint anywhere in the codebase even in the _.mjs_ files without any errors or issues 🤔

### Expected Behaviour

The debugger stops at the designated breakpoint.

### Actual Behaviour

Error appears in IDE console and the debugger just keeps going and does not stop on a breakpoint.

### Versions
* Atom: 1.26.0.beta-2
* Client OS: High Sierra 10.13.4
* atom-ide-ui: 0.11.0

### Additional Details

```
Community Packages (63) /Users/robert/.atom/packages
├── atom-chai-snippets@0.3.0 (disabled)
├── atom-ide-debugger-node@0.7.1
├── atom-ide-debugger-react-native@0.7.1
├── atom-ide-ui@0.11.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-ternjs@0.18.3 (disabled)
├── autocomplete-json@5.5.2
├── autocomplete-modules@2.0.0
├── autocomplete-sql@0.5.0
├── base16-syntax@1.8.1
├── blame@1.0.1
├── build@0.70.0
├── build-dockerfile@1.0.1
├── build-make@0.13.0
├── color-picker@2.3.0
├── data-atom@0.29.0
├── docblockr@0.13.7
├── editorconfig@2.2.2
├── file-icons@2.1.18
├── firestore-rules-grammar@0.3.0
├── git-plus@7.10.2
├── git-projects@1.17.0
├── github-user-datatip@0.3.2
├── go-debug@1.6.1
├── go-plus@5.8.3
├── gruvbox-plus-syntax@1.3.1
├── highlight-selected@0.13.1
├── ide-css@0.3.0
├── ide-docker@0.0.2
├── ide-go@0.7.0
├── ide-json@0.2.1
├── ide-typescript@0.7.6
├── ide-yaml@0.4.3
├── indent-guide-improved@1.4.13
├── js-hyperclick@1.13.0
├── language-babel@2.84.0 (disabled)
├── language-diff@0.7.0
├── language-docker@1.1.8
├── language-dotenv@1.1.1
├── language-gitignore@0.3.0
├── language-graphql@0.10.0 (disabled)
├── language-ini@1.19.0
├── language-terraform@0.8.1
├── linter-coverage@0.1.0
├── linter-eslint@8.4.1
├── linter-markdown@5.2.0
├── linter-package-json-validator@2.0.0
├── linter-shellcheck@1.4.7
├── linter-swagger@0.4.2
├── linter-terraform-syntax@1.2.2
├── linter-travis-lint@1.0.0
├── minimap@4.29.8
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── minimap-linter@2.1.3
├── pretty-json@2.0.0
├── sort-lines@0.18.0
├── standardjs-snippets@2.6.2
├── sync-settings@0.8.6
├── teletype@0.12.2
├── todo-show@2.3.0
└── tree-view-autoresize@2.3.0
```

**Comment by robertrossmann** [comment]
Another way to circumvent the initial exception is to use a `debugger` statement in the code. Once that statement is reached, I can set breakpoints in the original source files without any issues.

I was able to replicate this behaviour on the same project also in VS Code so I fear that reporting this problem here won't be of much help... 😥

**Comment by mostafaeweda** [comment]
Indeed, as the node debugger here is ported from VSCode's node debugger
