### ISSUE TITLE
debugger:toggle doesn't work like other common toggle actions

### ISSUE THREAD

**Issue by EvilOatmeal** [facebook-atom/atom-ide-ui#213]
### Description

The `debugger:toggle` action will add/remove the debugger from the panel without checking if it's focused or not, or if the panel is opened/closed.

If the panel is closed the debugger will be removed with the panel still closed so it seems like the action didn't do anything.

If the panel is open but the debugger is not focused the debugger will be removed instead of focused.

Other common toggle actions, like `diagnostics:toggle-table` from this package, or `tree-view:toggle`, will check if the panel is open/closed and the panel tab is focused/unfocused and do more appropriate things for the scenario.

### Expected Behavior

**If the debugger isn't focused:**
1. If the panel isn't opened, open it
2. Focus the debugger

**If the debugger is focused:**
1. Close the panel the debugger is in

### Actual Behavior

The toggle action only checks if the debugger is in the panel or not.

### Versions

* Atom: 1.25.1
* Client OS: Mac OS X 10.11.6 (El Capitan)
* atom-ide-ui: 0.11.0

### Additional Details

```
Community Packages (42) /Users/eom/.atom/packages
├── angularjs@0.5.3 (disabled)
├── atom-ide-debugger-node@0.7.1
├── atom-ide-ui@0.11.0
├── atom-open-related-files@0.1.0
├── atom-quokka@1.0.70 (disabled)
├── autocomplete-paths@2.12.2
├── busy-signal@1.4.3
├── color-picker@2.3.0
├── docblockr@0.13.7
├── double-tag@1.1.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── eom-atom-syntax@0.0.0
├── expand-region@0.4.0
├── file-icons@2.1.18
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-typescript@0.7.6
├── intentions@1.1.5
├── js-refactor@0.8.1
├── language-docker@1.1.8
├── language-lua@0.9.11
├── language-stylus@0.2.0
├── line-diff-details@1.9.0 (disabled)
├── linter@2.2.0 (disabled)
├── linter-docker@0.3.2
├── linter-eslint@8.4.1
├── linter-ui-default@1.7.1 (disabled)
├── multi-file-open@0.1.1
├── open-recent@5.0.0
├── pigments@0.40.2
├── refactor@0.11.5
├── related@0.3.5
├── relative-numbers@0.9.0
├── sort-lines@0.18.0
├── split-diff@1.5.2
├── switch-quotes@0.1.0
├── teletype@0.12.2 (disabled)
├── todo-show@2.3.0 (disabled)
├── tree-view-filter@0.5.3 (disabled)
└── vim-mode-plus@1.32.0
```

**Comment by ebluestein** [comment]
Unfortunately the debugger doesn't behave like other panels because the debugger contains many panels, which can be torn out and moved around the UI. There is no single notion of its parent panel being opened or collapsed because some panels could be visible, while others are not.

So the current behavior is intentional - it looks at if the debugger is present in the UI or not, and toggles that state.
