### ISSUE TITLE
Shortcut key conflict

### ISSUE THREAD

**Issue by linjialiang** [facebook-atom/atom-ide-ui#217]
`F11`  Conflicts with full screen shortcut keys

**Comment by ebluestein** [comment]
This is by design, we take F11 because this is the key used in Chrome Devtools and other debugging tools people are used to.

If the conflict is a problem for you, you can assign a different hotkey for this action in your keymap.json file

**Comment by linjialiang** [comment]
But the `atom` is not the case, the `atom` will  ` F11 `  as global shortcuts
