### ISSUE TITLE
Insert script directly to open terminal

### ISSUE THREAD

**Issue by saeidamiri1** [facebook-atom/atom-ide-ui#220]
Have you defined any shortcut key to paste (insert) scripts to language in terminal to run. Termination (https://atom.io/packages/termination) provides terminals for Atom, and by `termination:insert-text` can paste (insert) the script directly to the open terminal. Unlike termination's terminal that does not allows copy the result from terminal, your terminal does and can be very useful for running the scripts.

**Comment by pelmers** [comment]
The nuclide-terminal Atom service API provides open and close functions. see https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/types.js#L43

Here's a little example to get you started.
```
atom.packages.serviceHub.consume('nuclide-terminal', '0.0.0', x => window.terminal = x);
terminal.open({initialInput: "hi world"});
```

You can consume the service and provide commands in separate atom package or script!

**Comment by pelmers** [comment]
closing, feel free to re-open if that isn't clear answer
