### ISSUE TITLE
[Feature request] Button to open the Terminal

### ISSUE THREAD

**Issue by niccolomineo** [facebook-atom/atom-ide-ui#224]
Could atom-ide add support for opening the terminal from the bottom status bar via a button (like in other packages) or something quicker than the top menu?

Ref: https://atom.io/packages/platformio-ide-terminal

**Comment by lloiser** [comment]
you can use the keyboard short cuts:
mac: <kbd>ctrl-shift-t</kbd>
win/linux: <kbd>alt-shift-t</kbd>

**Comment by niccolomineo** [comment]
Cheers.

**Comment by pelmers** [comment]
You can easily make a custom button for the status bar that would do this! And the quickest way to open terminal is likely keyboard shortcut as @lloiser suggests.

Here's a script example I shared previously:
```
atom.packages.serviceHub.consume('nuclide-terminal', '0.0.0', x => window.terminal = x);
terminal.open({initialInput: "hi world"});
```
see terminal API here: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/types.js#L42-L45
