### ISSUE TITLE
atom-ide-ui 0.11.1 installation fails in windows 7 64 bits 6.1.7601

### ISSUE THREAD

**Issue by rcoborod** [facebook-atom/atom-ide-ui#225]
### Before Submitting
I have installed several languaje packages and they work.. but not the core atom-ide-ui... I guess I'm missing some funtionallities...

Perhaps it needs admin privileges...

### Description
just click over install for package atom-ide-ui

### Expected Behavior
Install properly

### Actual Behavior
installation fails in windows but works properly in Ubuntu 18.04 ( same version and release )

### Versions
* Atom: 1.26.0
* Client OS: Windows 7 64 bits 6.1.7601
* atom-ide-ui: 0.11.1

### Additional Details
* Installed packages (`apm ls --installed`):
Similar behavior has been suffered trying to install atom-ide-ui 0.11.1 today over Windows 7 64 bits Version OS 6.1.7601..

just for info:

Installing “atom-ide-ui@0.11.1” failed.Hide output…
C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi
`-- (empty)

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\package.json'
npm WARN apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi No description
npm WARN apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi No repository field.
npm WARN apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi No README data
npm WARN apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\nXXXXXX\\AppData\\Local\\atom\\app-1.26.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\nXXXXXX\\AppData\\Local\\atom\\app-1.26.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\nXXXXXX\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\nXXXXXX\\.atom\\.apmrc" "install" "C:\\Users\\nXXXXXX\\AppData\\Local\\Temp\\d-118324-8968-17gl28q.ide1z1714i\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\babel-runtime
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\babel-runtime' -> 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\.babel-runtime.DELETE'
npm ERR!     at moveAway (C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\babel-runtime' -> 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\.babel-runtime.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\babel-runtime' -> 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\.babel-runtime.DELETE'
npm ERR!     at moveAway (C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\nXXXXXX\AppData\Local\atom\app-1.26.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\babel-runtime' -> 'C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\node_modules\atom-ide-ui\node_modules\.babel-runtime.DELETE'
npm ERR!     at Error (native) parent: 'atom-ide-ui' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nXXXXXX\AppData\Local\Temp\apm-install-dir-118324-8968-fs0oyh.f6lxe6ogvi\npm-debug.log
npm ERR! code 1

**Comment by pelmers** [comment]
looks like it's this one, https://github.com/facebook-atom/atom-ide-ui/issues/208

see workaround here: https://github.com/atom/atom/issues/14913
