### ISSUE TITLE
upgrade failure and work around

### ISSUE THREAD

**Issue by odysseus55** [facebook-atom/atom-ide-ui#226]
Upgrading to atom-ide-ui 0.11.1 from 0.11.0 fails with: 
EACCES: permission denied, unlink '/home/XXX/.atom/packages/atom-ide-ui/.yarnrc' 
whrere XXX is user login name.

It failed with same error upgrading to 0.11.0 but I do not recall what the original version was.

All files= owner:group in  '/home/XXX/.atom/packages/atom-ide-ui/.yarnrc' is root:root

Workaround is sudo apm install atom-ide-ui

Linux Mint 18.1 Cinnamon 64bit 
Cinnamon ver 3.2.7
Linux kernel 4.4.0-116generic
Atom 1.26.0

Community Packages (4) /home/XXX/.atom/packages
├── atom-beautify@0.32.2
├── atom-ide-ui@0.11.1
├── autocomplete-cfml@0.5.0 (disabled)
└── language-cfml@0.23.0

**Comment by hansonw** [comment]
Thanks for leaving a workaround! I believe it's the issue here though: https://github.com/atom/atom/issues/14913
