### ISSUE TITLE
WSL Terminal

### ISSUE THREAD

**Issue by sGerli** [facebook-atom/atom-ide-ui#232]
### Description
I can't seem to find a way to change Atom-ide's default terminal to [WSL](https://docs.microsoft.com/en-us/windows/wsl/about).

### Expected Behavior
Ability to change default terminal and environment to WSL.

### Actual Behavior
I couldn't find a way to change it.

### Versions
* Atom: 1.26.0
* Client OS: Windows 10
* atom-ide-ui: 0.11.1

### Additional Details
* Visual Studio Coda has this feature and it's really useful for developing with node.js and using other linux only compiler like the Pebble SDK.

**Comment by pelmers** [comment]
I'm not sure where home directory is on windows, but you should be able to follow directions here to specify a custom shell command: https://nuclide.io/docs/features/terminal/#custom-shell.

for the interested, here's the line that implements the logic: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/pty-service/shellConfig.js#L32

**Comment by ebluestein** [comment]
You can use that custom shell logic on Windows. Create the file under %userprofile%

You'll want to specify something like this:
```

{
  "command": [
    "C:\\windows\\system32\\cmd.exe",
    "/c",
    "bash"
  ]
}
```
