### ISSUE TITLE
Cannot open Atom Ide Terminal: Cannot find module nuclide-prebuilt-libs v57

### ISSUE THREAD

**Issue by Znert** [facebook-atom/atom-ide-ui#241]
### Description
Opening a new terminal gives the following error message:

    Error starting process:
    Error: Cannot find module '[my home folder]/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'

Looking for said file, I found that a `pty-v0.1.4-node-v51-linux-x64` folder exists, but I did not find anything locally or on the web about a v57.

### Expected Behavior
A terminal should open.

### Actual Behavior
I get the above error.

### Versions
* Atom: 1.26.1 x64
* Client OS: Manjaro (Arch) Linux
* atom-ide-ui: 0.11.2

### Additional Details
My OS as well as Atom are a fresh install, so it may be possible that undocumented dependencies are missing.

**Comment by pelmers** [comment]
The cause is a node version mismatch, we only distribute the prebuilt binary for node v7. for a fix see https://github.com/facebook/nuclide/issues/1431

**Comment by Znert** [comment]
Thanks for your super quick reply, but I'm still doing something wrong.

Via `nvm` I installed v7.10.1 and followed the steps as listed in https://github.com/facebook/nuclide/issues/1431#issuecomment-369427040 but I still get a version mismatch apparently. When I copy `pty.node` into the listed folder, I get the following error:

    For more info check out the docs: https://nuclide.io/docs/features/terminal
    Error starting process:
    Error: The module '/home/znert/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 51. This version of Node.js requires
    NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).

So sorry for asking again, but how do I fix this?

One thing I noticed, when listing `apm -v` I get `node 10.0.0 x64`, so Atom is (still) using v10? On the other hand, looking into `process.versions` in the Atom debugging console, it says `node:"8.2.1"`... So yeah, I'm a little confused about which version is now the "correct" one.

**Comment by Znert** [comment]
I have found the cause of the error:

Downloading and installing Atom via `pacman` (or presumably from AUR in general) Electron being fetched as dependency. But because the latest version of Electron is not the latest version Atom is built for, I get the above error.

I have contacted the maintainer already about this issue, meanwhile if download and unpack the tar from the Atom homepage, everything works just fine.

**Comment by phyllisstein** [comment]
I've run into this again after installing the latest Atom beta, possibly as a consequence of the Electron upgrade:

```
Error starting process:
Error: Cannot find module '/Users/daniel/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-darwin-x64/pty.node'
```

I've tried reinstalling `atom-ide-ui`, running `apm rebuild` in the module directory, and clearing Atom's caches, but nothing seems to help. I'd be grateful for any suggestions!

**Comment by hansonw** [comment]
Sorry, this needs a new release! Should be out tomorrow.

**Comment by phyllisstein** [comment]
Thanks so much for the update! Looking forward to it.

**Comment by LostPlayer99** [comment]
Even after updating to the latest atom-ide-ui version (0.12.0) there is still a error.

`Error starting process:
Error: A dynamic link library (DLL) initialization routine failed.
[my home folder]\.atom\packages\atom-ide-ui\node_modules\nuclide-prebuilt-libs\pty\build\pty-v0.1.4-node-v57-win32-x64\pty.node`

# Versions
Atom: 1.28.0-beta0 x64
Client OS: Microsoft Windows [Version 10.0.16299.431]
atom-ide-ui: 0.12.0

**Comment by Znert** [comment]
Just as an update, I updated the plugin to 0.12 and I can now open the terminal, even with the "broken" atom from AUR with Electron 1.8.4.

Thanks for your work and the fix :)

**Comment by eduardoinnorway** [comment]
This should not even be an issue. I had same issue now. A terminal is the second most used thing besides the IDE, so a Terminal should not be dependent on 3rd part packages, it should be something natural in the IDE.

**Comment by sdrausty** [comment]
```
[sdrausty21:48~]$ pacman -Ss apm
extra/kapman 18.08.2-1 (kde-applications kdegames)
    A clone of the well known game Pac-Man
community/apm 2.1.3-2 [installed]
    Atom package manager
[sdrausty21:48~]$ apm install nuclide
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/lib/electron/version'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/bin/apm:10:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
[sdrausty21:52~]$ uname -mo
aarch64 GNU/Linux
```

**Comment by faisal2173** [comment]
anyone able to find the solution to this problem ?
