### ISSUE TITLE
Atom ide ui terminal assertion error

### ISSUE THREAD

**Issue by Viceriel** [facebook-atom/atom-ide-ui#243]
### Description
After click on new terminal I get an prompt with assertion window and whole atom crash.
![alt text](http://galavecer.xf.cz/portfolio/assertion.png "Assertion window")

Maybe worth to mention, this is my first day with new laptop. On my previous laptop(also windows) works terminal fine. 

On my new laptop I have as default installed VS2013 redistributable, so I install VS2015 redistributable, but terminal still caused assertion error prompt and atom crash, than I install VS2017 redistributable but terminal still crashing at same way.

### Expected Behavior
Terminal should open.

### Actual Behavior
Assertion error and atom crash.

### Versions
* Atom: 1.26.1
* Client OS: Windows 10
* atom-ide-ui: 0.11.2

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-ide-ui@0.11.2
├── color-picker@2.3.0
├── docblockr@0.13.7
├── file-icons@2.1.20
├── highlight-selected@0.13.1
├── ide-css@0.3.0
├── ide-typescript@0.7.6
└── minimap@4.29.8

**Comment by Viceriel** [comment]
Problem was at McAfee, which probably prohibit use of winpty.dll

**Comment by Bestshot99** [comment]
@Viceriel Can you give me the steps you used to get around McAfee? I'm having the same problem

**Comment by Viceriel** [comment]
@Bestshot99 I turn him off if I remember correctly.

**Comment by Bestshot99** [comment]
@Viceriel You completely disabled McAfee?
