### ISSUE TITLE
feature request: surface relevant auto-complete options

### ISSUE THREAD

**Issue by mgrip** [facebook-atom/atom-ide-ui#245]
👋 

First off this plugin is amazing, thanks for your contributions.

Wanted to get your thoughts on how the autocomplete options are sorted. It seems right now everything is just alphabetical - would it make sense to prioritize user-defined values? Ie in the below example, the list could be

* name
* price
* rating
* hasOwnProperty
* etc

Not 100% sure this would be better or not, but figured its worth discussing. Sometimes the list of built in properties/functions can be overwhelming, and I end up typing out the entire word since the thing I'm looking for isn't the 1st autocomplete option

![image](https://user-images.githubusercontent.com/13454680/40022060-dcb0e1b0-5794-11e8-964b-dda83ece7aa7.png)

**Comment by hansonw** [comment]
Closing this in favour of the issue on ide-flowtype, since atom-ide-ui has no interaction with autocomplete.
