### ISSUE TITLE
How to enable the Code Highlight feature?

### ISSUE THREAD

**Issue by roelmagdaleno** [facebook-atom/atom-ide-ui#247]
Hi, I already installed **atom-ide-ui** and installed some ide-languages, but the atom-ide-ui says that we can enable the **Code Highlight** and other features by adding this piece of code into our `package.json`:

```
"providedServices": {
  "code-highlight": {
    "versions": {
      "0.1.0": "provideCodeHighlight"
    }
  }
}
```

But which package.json? My project package.json or which one?

Then it says: `Then, in your package entry point, add:`, and for that is the same question.

Does anyone can help me to configure this feature? Thanks.

You can find the [Code Highlight docs here](https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/code-highlight.md).

**Comment by LaurentTreguier** [comment]
All features, like code highlighting, are to be implemented by the `ide-*` packages. If you have installed one and the code highlighting isn't showing, then those packages probably just don't provide this feature.
Which IDE package have you installed ?

**Comment by hansonw** [comment]
Yeah the instructions there are intended for `ide-*` authors. You can file an issue on the `ide-` package you have installed if you'd like them to provide code highlighting.
