### ISSUE TITLE
Code action tips triggered by command attach to mouse cursor not text cursor

### ISSUE THREAD

**Issue by tylerFowler** [facebook-atom/atom-ide-ui#248]
I'm finding that as of Atom Beta 1.28.0-beta0 when I hover over something with an available code action and use the `Diagnostics: Show Actions at Position` command the popup menu appears at my mouse cursor instead of my text cursor (expected behavior).

### Versions
* Atom: 1.28.0-beta9
* Client OS: MacOS High Sierra 10.13.4 (17E202)
* atom-ide-ui: 0.11.2

**Comment by hansonw** [comment]
Fixed in 52582a7f46398909526f41a64781c7964251b9df, will be out tomorrow.

**Comment by tylerFowler** [comment]
Can confirm this is fixed as of v0.12.0
