### ISSUE TITLE
Command to send code to Terminal

### ISSUE THREAD

**Issue by sasquatch666** [facebook-atom/atom-ide-ui#256]
I am working on a grammar package and am hoping to integrate it with the atom-ide-terminal.

What I would like is to configure the terminal to launch with a specified command when launched from this grammar (or just some option to launch the terminal with a set command, e.g. to launch with a python shell or similar).

I would also like to have commands to send certain blocks of code (selection, line, etc.) to the terminal.

Are there hooks available to make this easy? I'm not a js whiz so I could easily have missed it, but I've been poring over the code and I haven't found anything.

### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.

This issue pertains to the atom-ide-terminal, independent of any "ide-" package.

### Versions
* Atom: 1.27.1
* Client OS: macOS 10.13.4
* atom-ide-ui: 0.12.0

**Comment by pelmers** [comment]
yes, the terminal api provides ability to run a command or pre-fill text in the terminal.

here's an example to get you started, try running it in the dev console (cmd-alt-i):

```
atom.packages.serviceHub.consume('nuclide-terminal', '0.0.0', x => window.terminal = x);
terminal.open({initialInput: "hi world"});
```

Here's the api for the `open` method: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/types.js#L15-L32

you may be interested in the 'command' and 'initialInput' fields

**Comment by sasquatch666** [comment]
Thanks for the quick response! This is exactly what I'm going for. A couple of quick follow-ups,

1: if I try to send a string for a command that will actually execute (ex "hi world\n") I get an error message about including "potentially malicious" characters, is there a way around this?

2: Is there a way to similarly send input to a terminal that is already open?

**Comment by pelmers** [comment]
1. The 'command' field will let you run a command in the terminal directly, see its interface at https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/pty-service/rpc-types.js#L32-L35. e.g. `terminal.open({command: {file: '/bin/ls' args: ['~']})`
2. Not possible beyond hacky ways of pulling the 'terminal' object out of the dom (i.e. document.querySelector(".terminal-pane").terminal) and sending input to it, or finding the input element and sending keystroke events to it.

**Comment by sasquatch666** [comment]
Alright, I don't mind trying to put together something a little hacky.

Thanks for the clarification on the "command" field, I have it working now.
