### ISSUE TITLE
Cursor too big in terminal emulator

### ISSUE THREAD

**Issue by memeplex** [facebook-atom/atom-ide-ui#262]
Just a minor aesthetic annoyance.

![image](https://user-images.githubusercontent.com/2845433/40860521-0f332e7e-65bc-11e8-94e6-da2455847643.png)

My probably relevant settings:

* font family: ubuntu mono
* font scale: 1.2
* line height: 1.2

**Comment by pelmers** [comment]
hi, this particular piece of rendering comes from the xterm.js library: https://github.com/xtermjs/xterm.js, I suggest filing the issue there instead
