### ISSUE TITLE
Auto-Complete not working properly

### ISSUE THREAD

**Issue by KJ1010G** [facebook-atom/atom-ide-ui#267]
### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.
* If your issue is language-specific, please file an issue against
  the "ide-" language package you're using instead.

### Description
When i am typing some code, for example-
frame.setVi
at this point it would correctly show me the auto-complete options.
![issue_java_ide_atom](https://user-images.githubusercontent.com/38991076/41072835-d1553ffa-6a1d-11e8-9cbe-b89a17b835c9.png)
No problems till now.

### Expected Behavior
Now, when I press TAB/ENTER to auto-complete the highlighted option ( setVisible(Boolean b) in this example ) , it should correctly auto-complete in my code.

### Actual Behavior
But it doesn't approximately 70% of time. When i press TAB/ENTER, the options diss-appear.
![issue_java_ide_atom_2](https://user-images.githubusercontent.com/38991076/41073092-384ef27c-6a1f-11e8-9cbe-e11843d381c0.png)
Then i have to press, Ctrl+Space to make the options visible again. And choose the same option( if I choose some other and press TAB, then too nothing happens) again and then press TAB. Then it auto-completes.
Basically, 30% of time, auto-complete works when I press TAB on an option once.
And, 100% of time, auto-complete works when I press TAB on an option twice.
So, 70% (approx) of time i have to press TAB twice.

Also, this never happens when the option is of "language-java" package. The default atom package.
Those options get Auto-completed in first attempt always.

### Versions
* Atom: 1.27.2
* Client OS: Ubuntu 16.04LTS
* atom-ide-ui: 0.12.0

### Additional Details
* Installed packages (`apm ls --installed`):
Your package
'ide-java 0.8.3 Is --installed'
and core packages, nothing else

**Comment by hansonw** [comment]
Please report this in atom

**Comment by hansonw** [comment]
Please report this on atom/atom-languageclient - atom-ide-ui doesn't provide autocompletion, since it's part of Atom already.
