### ISSUE TITLE
How to change line height of the terminal text?

### ISSUE THREAD

**Issue by trusktr** [facebook-atom/atom-ide-ui#269]
Normally everything in Atom is stylable (f.e. line height) in `styles.less` because it's all DOM/HTML/CSS.

But Atom IDE's terminal is rendered with canvas, so I can't simply modify the line height of the text.

Is there a way to configure this?

**Comment by hansonw** [comment]
Yup, look for the "line height" setting in the terminal section of
atom-ide-ui settings.

See:
https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/package.json#L78
