### ISSUE TITLE
Atom-ide-outline-view should provide an option to disable toolbar button

### ISSUE THREAD

**Issue by aterenin** [facebook-atom/atom-ide-ui#27]
### Description
Atom-ide-outline-view creates a tool-bar button that I cannot disable. I use flex-tool-bar and prefer to define the location and order of the buttons myself. Other users may prefer to use the command palette instead of a button.

### Additional Details
It would be great to add an option so that a button is not automatically created. Thanks!

**Comment by hansonw** [comment]
:+1: Actually we'll just remove the toolbar icon, since it's inconsistently provided throughout this package.
