### ISSUE TITLE
Terminal drawing is very slow.

### ISSUE THREAD

**Issue by trusktr** [facebook-atom/atom-ide-ui#270]
### Description

Terminal rendering is slooooooooooooow.

### Expected Behavior

It should render fast, at least at the same speed as text editor tabs.

For example, when highlighting a random block of text in terminal, the line highlight is slow to draw compared to highlighting text in a regular text editor tab.

### Actual Behavior

It's sloooooooooooow. Why is it so slow?

Maybe this isn't Atom IDE's fault. What terminal lib are you using? Maybe I can file there if it's a problem with that lib.

Maybe there's another lib Atom-IDE can use instead? The experience is sub par.

I've tried other terminal packages for Atom, and they have the same problem. I am guessing they're using the same terminal lib because they render and feel the same.

### Versions

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.27.2",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.32.0",
  "vmpConfig": {
    "automaticallyEscapeInsertModeOnActivePaneItemChange": true,
    "keymapYToYankToLastCharacterOfLine": true,
    "wrapLeftRightMotion": true,
    "blackholeRegisteredOperators": [],
    "startInInsertModeScopes": [],
    "charactersToAddSpaceOnSurround": [],
    "highlightSearchExcludeScopes": [],
    "flashOnOperateBlacklist": []
  },
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "atom-ide-ui: 0.12.0",
    "atom-ide-busy-signal: 0.0.0",
    "atom-ide-code-actions: 0.0.0",
    "atom-ide-code-format: 0.0.0",
    "atom-ide-code-highlight: 0.0.0",
    "atom-ide-console: 0.0.0",
    "atom-ide-datatip: 0.0.0",
    "atom-ide-debugger: 0.0.0",
    "atom-ide-definitions: 0.0.0",
    "atom-ide-diagnostics: 0.0.0",
    "atom-ide-diagnostics-ui: 0.0.0",
    "atom-ide-find-references: 0.0.0",
    "atom-ide-global: 0.0.0",
    "atom-ide-outline-view: 0.0.0",
    "atom-ide-signature-help: 0.0.0",
    "atom-ide-terminal: 0.0.0",
    "hyperclick: 0.0.0",
    "atom-vim-like-tab: 1.5.1",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "ide-css: 0.3.0",
    "ide-html: 0.4.2",
    "ide-json: 0.2.1",
    "ide-typescript: 0.7.6",
    "ide-vue: 0.1.8",
    "indent-guide-improved: 1.4.13",
    "keystroke: 0.4.0",
    "minimap: 4.29.8",
    "minimap-highlight-selected: 4.6.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "one-tab: 0.10.0",
    "pigments: 0.40.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "teletype: 0.13.2",
    "terminal-tab: 0.5.6",
    "tree-view-git-status: 1.5.0",
    "vim-mode-plus: 1.32.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "editorconfig: 2.2.2",
    "language-pug: 0.0.22",
    "language-vue: 0.23.1",
    "ex-mode: 0.18.0",
    "paner: 1.0.0",
    "advanced-open-file: 0.16.8"
  ]
}
```

</details>

**Comment by trusktr** [comment]
It seems to be slower and slower depending on how much output the terminal has. The more lines it has, the slower it gets. This is unlike Terminal or iTerm in macOS.

**Comment by pelmers** [comment]
The terminal packages for Atom/Vscode likely all use xterm.js which on many hardware combinations hits issues with Electron/canvas rendering. Their next release will include a DOM renderer that should help here when we include it.

**Comment by dfenster** [comment]
They're both slow for me on a surface pro 4, but the dom renderer is the slowest.

**Comment by hansonw** [comment]
v0.13.0 has a setting under the "Terminal" section to configure the renderer. As @pelmers please try the DOM renderer if the canvas renderer is causing issues for you.

<img width="874" alt="screen shot 2018-07-17 at 9 29 17 pm" src="https://user-images.githubusercontent.com/577378/42859544-7a74ab16-8a08-11e8-80d6-f10f1160a59b.png">

**Comment by wesgt** [comment]
Hi all, 
I try to set DOM renderer, but it still draw slowly.
is there anyone like me?

**Comment by tj** [comment]
Just a FYI (wasn't really using it anyway) but I had to disable the entire package to get fast typing back, something in there seemed to be slowing it down dramatically
