### ISSUE TITLE
Keybinding for datatip hover.

### ISSUE THREAD

**Issue by colbydehart** [facebook-atom/atom-ide-ui#274]
It seems that there is no command or keybinding to show a datatip. It would be nice if there was something like `'datatip:hover'` that you could use in a keybinding so that you can get type information in a file without having to touch a mouse.

**Comment by lloiser** [comment]
https://github.com/facebook-atom/atom-ide-ui/blob/40e6ca5fbdf95e3503a0155bf7eb51f796b2c5e3/modules/atom-ide-ui/pkg/atom-ide-datatip/keymaps/datatip.json#L1-L11

At least on my mac it works with <kbd>alt + cmd</kbd>

You can also have a look at `Settings -> Keybindings`. It contains all keybindings that are registered. 
![screen shot 2018-06-22 at 08 10 59](https://user-images.githubusercontent.com/3003233/41760464-d81e2b9e-75f3-11e8-872c-fa8933fa3882.png)

**Comment by colbydehart** [comment]
Okay, I had tried to use that command but for some reason it would not work, so I thought it did something else. Probably something in another plugin i have mucking things up. Will investigate further and see what plugin is causing the conflict. Thanks!
