### ISSUE TITLE
Exception thrown, regardless of which ide- packages installed/enabled

### ISSUE THREAD

**Issue by frost-byte** [facebook-atom/atom-ide-ui#277]
### Description
No matter which ide packages I have enabled/disabled (ide-css, ide-html, ide-typescript),
they all cause the same exception to be thrown.

```
Error: Message header must separate key and value using :
    at C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:65:17)
    at StreamMessageReader.onData (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:194:43)
    at Socket.<anonymous> (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
I believe this is caused because of my project directory structure.  The root directory contains a local defined package which is linked (npm link, yarn link, etc) and used in a sub directory. (So a recursion is happening)

I was able to extract the contents of the buffer that was leading to the exceptions, where you can see that the directory structure is being referenced in a circular manner:

```
<— Last few GCs —>

[13628:078B3110] 573401 ms: Mark-sweep 1076.6 (1354.8) -> 1076.5 (1354.8) MB, 801.9 / 0.2 ms allocation failure GC in old space requested
[13628:078B3110] 574240 ms: Mark-sweep 1076.5 (1354.8) -> 1076.5 (1323.3) MB, 838.6 / 0.2 ms last resort GC in old space requested
[13628:078B3110] 575071 ms: Mark-sweep 1076.5 (1323.3) -> 1076.5 (1315.3) MB, 830.5 / 0.2 ms last resort GC in old space requested

<— JS stacktrace —>

==== JS stack trace =========================================

Security context: 0EA5B091 
1: inflight [C:\Users\xxxx.atom\packages\ide-typescript\node_modules\inflight\inflight.js:~7]
[pc=389204DB](this=0E385525 ,key=576F50E9
<String[459]: readdir\x00
D:/repositories/daterangepicker/website-angular/node_modules/knockout-daterangepicker-fb/website-angular/node_modules/knockout-daterangepicker-fb/website-angular/node_modules/knockout-daterangepicker…
```

### Expected Behavior
No flood of red error boxes that make Atom look like its being bathed in blood, or make me feel like I'm in a nightmare, where every stop light on my trip is red.

### Actual Behavior
A continual stream of error toasts mentioning the exception. (Even when I have another application focused)

### Versions
* Atom: 1.28.0
* Client OS: Microsoft Windows 10 Home
* atom-ide-ui: 0.12.0

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (56) C:\Users\Brian\.atom\packages
├── atom-autocomplete-php@0.25.6 (disabled)
├── atom-beautify@0.32.5
├── atom-debug-ui@1.0.4
├── atom-handlebars@1.3.0 (disabled)
├── atom-ide-ui@0.12.0
├── atom-jinja2@0.6.0
├── atom-material-syntax@1.0.8
├── atom-material-syntax-dark@1.0.0
├── atom-material-ui@2.1.3
├── atom-save-all@0.4.1 (disabled)
├── atom-ternjs@0.18.3 (disabled)
├── atom-typescript
├── autocomplete@0.47.0 (disabled)
├── autocomplete-modules@2.1.0
├── autocomplete-php@0.3.7 (disabled)
├── bug-report@0.7.1
├── docblockr@0.9.1
├── file-icons@2.1.21
├── fonts@3.0.3 (disabled)
├── git-plus
├── highlight-bad-chars@1.0.7 (disabled)
├── hyperclick@0.1.5
├── ide-html@0.4.2
├── ide-php@0.7.14
├── ide-typescript@0.7.6
├── intentions@1.1.5
├── isotope-ui@2.8.5
├── jquery-snippets@11.0.0
├── language-ansible@0.2.2
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.1
├── linter-htmlhint@1.4.0
├── linter-js-yaml@1.3.0
├── linter-php@1.5.1 (disabled)
├── linter-tslint@1.9.1
├── markdown-preview-plus
├── markdown-writer@2.7.3 (disabled)
├── merge-conflicts@1.4.5
├── monokai@0.24.0
├── monokai-dark@1.5.0
├── package-cop@0.2.10
├── php-cs-fixer@4.1.1
├── php-debug@0.3.5
├── php-hyperclick@1.2.1
├── php-integrator-annotations@1.2.0
├── php-integrator-autocomplete-plus@1.6.2
├── php-integrator-base
├── php-integrator-navigation@1.2.1
├── php-integrator-refactoring@1.4.1
├── php-twig@4.0.0
├── project-manager@3.3.6
├── sass-autocompile@0.13.5
├── symbol-gen@1.3.1 (disabled)
├── symbols-tree-view (disabled)
├── todo-show@2.3.0
└── xml-formatter@0.11.0

* apm  1.19.0
* npm  3.10.10
* node 6.9.5 ia32
* python 2.7.12
* git 2.12.0.windows.1
* visual studio 2013

**Comment by hansonw** [comment]
I'm pretty sure this error is coming from `ide-html` - are you sure you disabled it? The stack trace is clearly coming from there:

```
    at MessageBuffer.tryReadHeaders (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:65:17)
```

Anyhow maybe you can try filing an issue on `atom-languageclient`, as `atom-ide-ui` doesn't control the actual communication with the language servers.

**Comment by Arcanemagus** [comment]
@frost-byte Your circular directory reference is from the project you have open. Did you use an alternative package manager that uses symlinks instead of `npm`? This isn't an issue here, with Atom, or any package installed in it, but is a bug in how whatever package manager you used installed the dependencies in your `D:/repositories/daterangepicker/website-angular` project.
