### ISSUE TITLE
关于 atom-ide-ui 报错的提示的一点建议

### ISSUE THREAD

**Issue by linjialiang** [facebook-atom/atom-ide-ui#280]
> @hansonw 你好 `atom-ide-ui` 在处理报错时提醒功能缺少目录和文件报错变化，下面我举个例子
> - 1. 如果 `app\demo\Index.php` 下的 `Index.php` 出现错误：
> - 2. 当前文件 `Index.php` 底部会出现一个特殊颜色的波浪线
> - 3. 当前文件的所有上层目录的底部也跟着出现一个特殊颜色的波浪线

> 这是 `phpstrom` 下的报错提示

![default](https://user-images.githubusercontent.com/8848263/42143581-76b68e80-7de8-11e8-9703-a5b401276d95.png)

> atom 编辑器的 `linter` 插件已经支持这种报错方式

**Comment by hansonw** [comment]
Dupe of #272?
