### ISSUE TITLE
Support for "Code Lens"

### ISSUE THREAD

**Issue by Gert-dev** [facebook-atom/atom-ide-ui#288]
[Code Lens](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeLens) allows language servers to return information to the client regarding actions (commands) that can be executed in relation to specific ranges of code. The definition for this is rather broad; it could be something like `Run test` next to a test method, but it could also be something like `Navigate to parent method` for overridden methods.

The flow of the request:

1. Client requests code lenses via `textDocument/codeLens`
2. Server returns them, each have a text range, an optional command and optional data
3. If `command` is not filled in yet, client can only indicate to user that "something is possible", if the user wants to know what is and interacts with it, client sends `codeLens/resolve` to resolve the appropriate command
4. Show the user some sort of gutter marker or inline floating text related to the actions that could be taken according to the code lens (a title can be extracted from the attached `command`); as there could be many, something like [intentions](https://github.com/steelbrain/intentions/) when multiple lenses are present may be in order
5. If user selects code lens to be executed, the underlying command is sent to the server (via `workspace/executeCommand`, I believe)
6. After that, the handling of the command is the same as (I believe) is already supported by atom-ide-ui; implementation depends on the client and server and needs to be handled by the language server client package individually, as there are no standard commands

Some examples of things that could be done with this:

* [vscode-phpunit](https://github.com/recca0120/vscode-phpunit) uses code lenses to support running PHPUnit tests inline
* [Serenata shows annotations](https://serenata.gitlab.io/#annotations) in the gutter that could be considered code lenses and allow navigating to overridden methods, implemented interface methods and overridden properties

**Comment by mostafaeweda** [comment]
There's no plan to support this in Atom IDE in the near future - hence, closing
