### ISSUE TITLE
None of the formatters can work

### ISSUE THREAD

**Issue by tonytonyjan** [facebook-atom/atom-ide-ui#29]
### Description
Installed atom IDE today, and none of formatters can work (Java, C#, etc).

### Expected Behavior
Codes should be formatted.

### Actual Behavior
It keeps showing "Failed to format code: No code formatting providers found!".

### Versions
* Atom: 1.19.1
* Client OS: macOS Sierra
* atom-ide-ui: 0.3.1

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by hansonw** [comment]
@tonytonyjan Have you installed `ide-csharp` (https://github.com/atom/ide-csharp) or `ide-java` (https://github.com/atom/ide-java)? `atom-ide-ui` provides no code formatters by itself; you have to install a language service to match it.

Although I noticed you're on 1.19.1, so you need to upgrade first... Both `ide-java` and `ide-csharp` require Atom 1.21-beta+.

**Comment by tonytonyjan** [comment]
@hansonw Thanks for your kind reminding.

Sorry, I am not an English native speaker, I guess I was misled by README file:

> Packages based on https://github.com/atom/atom-languageclient should work out of the box with `atom-ide-ui` installed.

I thought it means that we only need to install `atom-ide-ui` then everything will work without a configuration.

**Comment by hansonw** [comment]
Yeah I'll add a requirement to the 'getting started' section ;)
