### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of null

### ISSUE THREAD

**Issue by MeirBon** [facebook-atom/atom-ide-ui#293]
[Enter steps to reproduce:]

1. Open a terminal window
2. type 'exit' and press enter

Seems like terminal exits are not handled properly.

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: linux 4.17.6-82.current
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of null

```
At /home/meir/.atom/packages/atom-ide-ui/node_modules/xterm/lib/InputHandler.js:183

TypeError: Cannot read property 'buffer' of null
    at InputHandler.parse (/packages/atom-ide-ui/node_modules/xterm/lib/InputHandler.js:183:37)
    at Terminal._innerWrite (/packages/atom-ide-ui/node_modules/xterm/lib/Terminal.js:841:32)
    at /packages/atom-ide-ui/node_modules/xterm/lib/Terminal.js:826:23
```

### Commands

```
     -0:47 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui)
     -0:40.7.0 core:confirm (input.hidden-input)
  2x -0:15.2.0 atom-ide-terminal:new-terminal (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui)
```

### Non-Core Packages

```
atom-ide-debugger-native-gdb 0.7.3 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
file-icons 2.1.22 
ide-cquery 0.13.5 
ide-html 0.4.2 
ide-rust 0.18.0 
language-rust 0.4.12 
```

**Comment by brianchenlee** [comment]
@MeirBon Thanks for reporting this! It looks like this issue was also filed here: https://github.com/Microsoft/vscode/issues/54132 with a fix here: https://github.com/xtermjs/xterm.js/pull/1578, so we'll inherit this once we update the version.

**Comment by MeirBon** [comment]
@brianchenlee Alright, great!
