### ISSUE TITLE
Path resolving doesn't (always) work / doesn't cache

### ISSUE THREAD

**Issue by francoism90** [facebook-atom/atom-ide-ui#294]
### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.
* If your issue is language-specific, please file an issue against
  the "ide-" language package you're using instead.

### Description
The cursor only shows as loading, no console error when hovering with CTRL (command).
See screenshot: https://drive.google.com/open?id=1Z90CFTW1DVdxpSH93j58ua2IBFC2288D

### Expected Behavior
On click, do path resolving.
If it doesn't work, it would be nice to have some sort of message or index in statusbar. :)

### Actual Behavior
Just a loading cursor, waiting for index to be successful.
Also it doesn't seem to cache? Is this normal? `node_modules` is sometimes missing.

### Versions
* Atom: `atom 1.28.2-1`
* Client OS: Arch Linux
* atom-ide-ui: `0.13.0`

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (22) /home/archie/.atom/packages
├── atom-autocomplete-php@0.25.6
├── atom-beautify@0.32.5
├── atom-ide-ui@0.13.0
├── change-case@0.6.5
├── copy-path@0.5.1
├── custom-title@1.0.1
├── file-icons@2.1.22
├── highlight-selected@0.14.0
├── ide-bash@1.0.11
├── ide-php@0.7.14
├── ide-typescript@0.7.6
├── ide-vue@0.1.9
├── language-blade@0.40.0
├── language-jade@0.7.3
├── language-vue@0.23.1
├── markdown-preview-plus@3.3.3
├── open-recent@5.0.0
├── php-cs-fixer@4.1.1
├── pigments@0.40.2
├── sort-lines@0.18.0
├── sync-settings@0.8.6
└── todo-show@2.3.0
```

**Comment by francoism90** [comment]
Turns out this was an issue with SMB-share, using project on local goes a lot faster.

The cache question however remains. :)

**Comment by pelmers** [comment]
We're looking at improving consistency/behavior of the hyperclicking this week, so I'm merging this into an internal task.
