### ISSUE TITLE
Spawn terminal below?

### ISSUE THREAD

**Issue by naquiroz** [facebook-atom/atom-ide-ui#297]
### Simple Question
Is there a way to open up a new terminal on a pane below? I tried key-mapping, but I couldn't manage to find the context o which to place.

**Comment by pelmers** [comment]
Yep, I suggest a custom keymapping for this which you could register in a an init.js script. The terminal opener API takes a location, see this [comment](https://github.com/facebook-atom/atom-ide-ui/issues/256#issuecomment-392225513) and the api here: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/types.js#L43

A snippet to get you started in the dev console (cmd-alt-i):
```
atom.packages.serviceHub.consume('nuclide-terminal', '0.0.0', x => window.terminal = x);
terminal.open({defaultLocation: "bottom"});
```

Please re-open if this is still an issue!

**Comment by naquiroz** [comment]
Ok so I'm almost there, however im getting a single error.
![image](https://user-images.githubusercontent.com/29825816/43621348-eb18c6f6-96a4-11e8-8b97-72aa5f686883.png)

**Comment by matthewwithanm** [comment]
@wbinnsmith is working on something for this 🙂

**Comment by naquiroz** [comment]
@matthewwithanm Nice, looking foward to that feature. By the way, I found my error, 
```javascript
atom.packages.serviceHub.consume('nuclide-terminal', '0.0.0', x => window.terminal = x);
terminal.open({defaultLocation: "bottom"});
```
is on javascript language, and my initscript is on coffeescript and the place that is throwing the error is ` x => window.terminal = x`. Do you know how to make that in coffee script?

**Comment by matthewwithanm** [comment]
You can just rename it to init.js and use JavaScript ☺️

**Comment by naquiroz** [comment]
@matthewwithanm decided to keep with coffee, and I did it! Code below.

**Comment by pelmers** [comment]
If you want to run the input immediately, you can pass it as a `command` instead of `initialInput` (which is just the text that is pre-filled)
This might work (untested):
```
command = {file: venv, args: [filePath]}
terminal.open({cwd: currentPath, command: command, defaultLocation: "bottom"})
```
