### ISSUE TITLE
Atom ide ui issue when scrolling through the suggested methods

### ISSUE THREAD

**Issue by HamenderSingh** [facebook-atom/atom-ide-ui#30]
### Description
The screen where all the methods starting from particular letters are shown, kind of jumps when tried to scroll down or up using keyboard up and down keys.
To reproduce, go to the last line of a python file. Write a half function name you want use (example>> pandas.read_) try to select one method from the list of the methods suggested using up and down keys of keyboard.
Screenshots.
<img width="346" alt="screen shot 2017-09-14 at 11 48 14 am" src="https://user-images.githubusercontent.com/16079765/30415161-6acb6110-9944-11e7-8552-74a6af9f6897.png">

 After pressing down button
<img width="357" alt="screen shot 2017-09-14 at 11 48 28 am" src="https://user-images.githubusercontent.com/16079765/30415160-6acb08c8-9944-11e7-8f58-b0b893f03b18.png">

After pressing down button one more time
<img width="351" alt="screen shot 2017-09-14 at 11 48 35 am" src="https://user-images.githubusercontent.com/16079765/30415162-6acd8134-9944-11e7-9b02-250065ecc52a.png">

### Expected Behavior
The screen should be stable where the functions are listed means it shouldn't jump up and down when keyboard keys are used to scroll and select methods.

### Actual Behavior
At the moment the screen where the list of methods appear sort of jumps up and down when the keyboard keys are used to scroll and select method.

### Versions
* Atom: 1.20.0
* Client OS: Mac OS 10.12.6
* atom-ide-ui: 0.3.1

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (3)
├── atom-bracket-highlight@0.3.2
├── atom-ide-ui@0.3.1
└── ide-python@0.1.1

**Comment by hansonw** [comment]
Thanks for the report! Actually, autocompletion is already part of Atom (https://atom.io/packages/autocomplete-plus), so this isn't an atom-ide-ui issue.
Could you file this issue there instead? Thanks!
