### ISSUE TITLE
Nuclide terminal lines overlapping

### ISSUE THREAD

**Issue by chrisdoherty4** [facebook-atom/atom-ide-ui#301]
### Description
The Nuclide terminal lines are overlapping. 

![terminal](https://user-images.githubusercontent.com/3143682/44298801-c3bbb480-a2e1-11e8-9718-d1f6debb7f53.png)

### Versions
* Atom: 1.29.0
* Client OS: Ubuntu 18.04 Bionic Beaver
* atom-ide-ui: 0.13.0

### Additional Details
***Installed packages***
```
chrisdoherty:~$ apm ls -i -e
Community Packages (23) /home/chrisdoherty/.atom/packages
├── atom-beautify@0.33.0
├── atom-clock@0.1.16
├── atom-ide-ui@0.13.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── auto-detect-indentation@1.3.0
├── autocomplete@0.47.0
├── autocomplete-python@1.10.9
├── busy-signal@1.4.3
├── city-lights-syntax@1.1.8
├── city-lights-ui@1.5.3
├── docblockr@0.13.7
├── ide-css@0.3.0
├── ide-java@0.8.3
├── ide-python@1.0.0
├── ide-yaml@0.4.3
├── intentions@1.1.5
├── lint@0.0.1
├── merge-conflicts@1.4.5
├── minimap@4.29.8
├── python-tools@0.6.9
├── symbols-navigator@1.5.1
└── todo-show@2.3.0
```
* I am using the i3 window manager.

**Comment by pelmers** [comment]
Can you try suggestions in https://github.com/facebook-atom/atom-ide-ui/issues/261?

**Comment by chrisdoherty4** [comment]
Apologies for the delayed response. 

Changing the font under "Preferences -> Editor" didn't fix the issue. I restarted atom just to be sure but no joy - fonts still cut off. 

I'm also dubious of that actually fixing the issue given I've not changed any fonts, I'm just using the ones atom has selected to use so there is still an issue here.

**Comment by pelmers** [comment]
Hi, the setting to change is actually listed under the Atom-ide-ui package. The terminal's default font choice doesn't inherit from the editor window, and instead defaults to 'monospace'.

**Comment by chrisdoherty4** [comment]
Sorry! 
That worked no problem. Is there anything being done about the font it uses on install?

**Comment by pelmers** [comment]
No unfortunately the team here is very macos-centric, but if you'd like to poke around I would welcome a pull request. A starting point could be: https://github.com/facebook/nuclide/blob/master/modules/atom-ide-ui/pkg/atom-ide-terminal/package.json#L96

^Note that this is in the Nuclide repository -- atom-ide-ui is synced from Nuclide for each release.
