### ISSUE TITLE
code-highlight does't work

### ISSUE THREAD

**Issue by 4ern** [facebook-atom/atom-ide-ui#31]
### Description
The Feature Code Highlight does't work.

### Additional Details
Community Packages (9)
├── atom-clock@0.1.15
├── atom-ide-ui@0.3.1
├── editorconfig@2.2.2
├── highlight-selected@0.13.1 (disabled)
├── ide-typescript@0.6.1
├── language-typescript-grammars-only@1.6.0
├── project-manager@3.3.5
├── tab-control@0.6.10
└── toggler@0.3.0

**Comment by hansonw** [comment]
`ide-typescript` doesn't currently implement code highlights. (See: https://github.com/atom/ide-typescript/blob/master/package.json - there needs to be a `code-highlight` service).
Could you file this issue there instead?
