### ISSUE TITLE
About disable code format!!!

### ISSUE THREAD

**Issue by GHLandy** [facebook-atom/atom-ide-ui#319]
I got stuck today, as my code were format by atom-ide-ui automatically.

As I use eslint and prettier for that, I want to disable this feature.

But when I toggle this to `Never enable` as below, it dosn't work actually!

![image](https://user-images.githubusercontent.com/14830914/47624991-e62d4200-db5c-11e8-95e0-d7d51c06f30f.png)

And any way to solve this? help.

**Comment by mostafaeweda** [comment]
Are you sure that's `atom-ide-ui` triggering the format? could you debug a show a stack trace?
Our `FeatureLoader` should disable packages on `never enabled`

**Comment by GHLandy** [comment]
So sorry, I found it auto formatted by `language-babel` package.
