### ISSUE TITLE
no plain js formatters work

### ISSUE THREAD

**Issue by rynop** [facebook-atom/atom-ide-ui#35]
I have `ide-typescript` installed but when I try to format plain `.js` code (not `.ts`) I get a 

> no code formatting providers found

running v1.21.0-beta and adom-ide-ui 0.3.2

**Comment by damieng** [comment]
Yes, the ide-typescript package does not include any code formatters at this time as per the README.

**Comment by rynop** [comment]
@damieng thanks for the quick response. So does that mean there are no JS formatters compatible with `atom-ide-ui` ATM?

**Comment by damieng** [comment]
Not at this time but people can certainly create them.
