### ISSUE TITLE
Outline view: possible to view entries in original order?

### ISSUE THREAD

**Issue by bronson** [facebook-atom/atom-ide-ui#37]
### Description

Outline view is great, but (afaict) it can only show the entries sorted alphabetically.

I'd rather view the entries in their natural order in the file.  Is there any way to prevent the entries from being sorted?

Thanks for a fantastic package...  Things are really looking good.

### Versions
* Atom: 1.21.0-beta0
* Client OS: Mac
* atom-ide-ui: 0.3.1

**Comment by hansonw** [comment]
The outline view doesn't sort the entries - I suspect that atom/atom-languageclient is the one doing the sorting. right @damieng?

**Comment by hansonw** [comment]
Glad you like it though! :)

**Comment by damieng** [comment]
It wasn't intentionally reordering things but with the amount of post-processing to reconstruct the trees from the flattened structure it might well be happening.  If so we can address it in atom-languageclient

**Comment by damieng** [comment]
So OutlineViewAdapter isn't sorting them - in the case of the typescript server they're actually coming back in a weird order - top level of imports/class/variables are unsorted but them members of a class are sorted.

We could try and sort them ourselves using the source position order although that does mean taking control away from the underlying language server.  If there are languages in which a different order makes sense they'll have to reconfigure things to get what they want.

**Comment by damieng** [comment]
Let's track it over in atom-languageclient

**Comment by bronson** [comment]
That was fast!  Very impressive.  Looking forward to using it.
