### ISSUE TITLE
Status Bar - Change the error icon to a filled icon

### ISSUE THREAD

**Issue by mehcode** [facebook-atom/atom-ide-ui#38]
Currently the status bar looks like:

![screenshot from 2017-09-15 17-53-28](https://user-images.githubusercontent.com/753919/30507827-d01dd14c-9a3e-11e7-8f54-d1138ef808f0.png)

I'm suggesting it should look like:

![screenshot from 2017-09-15 17-55-54](https://user-images.githubusercontent.com/753919/30507849-27627746-9a3f-11e7-9a5d-f4b77df209a9.png)

The key reason is that filled vs. unfilled icons in the same component can be very jarring to look at.

**Comment by matthewwithanm** [comment]
Hey @mehcode! We actually recently added "nuclicon-stop" icon which is a filled version of the stop octicon. Makes sense to me to switch it over. 😊

**Comment by johnmichel** [comment]
Would it also be feasible to allow more customization with regards to placement of the icons in the Status Bar?  [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default) provided options for Left and Right that made the icons easier to see at a glance.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2V372R2H2o2Y142c1I32/%5Bf5f47665f6375cf92e02813a2a3932f6%5D_Screen%2520Shot%25202017-10-03%2520at%25209.41.09%2520AM.png)

**Comment by Arcanemagus** [comment]
@johnmichel That should be filed as a separate issue 😉.

**Comment by johnmichel** [comment]
@Arcanemagus Good call!  Created #69

**Comment by matthewwithanm** [comment]
Alright, should be good in next week's release! (:
