### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by mcheung63** [facebook-atom/atom-ide-ui#43]
unable to install in my latest atom running on windows 8.1
![bug](https://user-images.githubusercontent.com/1779905/30551180-874de3c8-9c4e-11e7-8f7d-87b085cb5ae3.png)

**Comment by Arcanemagus** [comment]
As stated in the README, you need to be running the beta version of Atom (v1.21.0-beta0).

**Comment by Arcanemagus** [comment]
@hansonw It looks like the readme for `ide-php` states that requirement, but `atom-ide-ui`'s README still says Atom v1.17 😛.

**Comment by mcheung63** [comment]
Thanks, sorry I skip that.

**Comment by damieng** [comment]
atom-ide-ui is quite happy to run in Atom 1.17 yes. The new things we added in Atom 1.21 were to support the ide-x packages (async package deactivation and file change monitoring).

@mcheung63 You can get Atom beta from https://atom.io/beta if you want to try it out.
