### ISSUE TITLE
Add tooltips to outline view icons

### ISSUE THREAD

**Issue by wldcordeiro** [facebook-atom/atom-ide-ui#48]
### Description
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Hovering over the icons in the outline view should show a tooltip (HTML title attribute?) that says what the icon represents (function, variable, class, etc)

I get the general idea of what my outline is showing but without a legend for the icons I have no idea what some represent.

### Actual Behavior
Nothing at all

### Versions
* Atom: 1.21beta1
* Client OS: OS X
* atom-ide-ui: 0.3.3

**Comment by hansonw** [comment]
This is a great starter task for anyone interested in contributing!
The icon rendering happens on https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/OutlineView.js#L289; my guess is that displaying `kind || icon` in a title attribute would be fine.

**Comment by hansonw** [comment]
I think this is done now!
