### ISSUE TITLE
Expose goToLocation activity as an Atom service

### ISSUE THREAD

**Issue by bronson** [facebook-atom/atom-ide-ui#50]
### Description

Hyperclicking is easy and satisfying, but it's not so easy to return from a hyperclick.

Symbols View solved this with `symbols-view:return-from-declaration`.  I really like that keystroke.

Maybe hyperclick could push its locations onto the sybmols view stack?

Or would there another way to make it easier to jump back from a hyperclick?  I'm happy to bang together a package or a PR but I'm not quite sure how to solve this.

**Comment by hansonw** [comment]
https://atom.io/packages/last-cursor-position is another package that solves this.
In Nuclide we had a 'navigation stack' package that would allow you to easily jump back and forth.. maybe we can consider releasing that as a separate package.

**Comment by bronson** [comment]
Well, last-cursor-position operates on every cursor move.  That's not really like `symbols-view:return-from-declaration` (unless I'm missing a way to configure last-cursor-position?)

Same question for the navigation stack package you refer to...  Did it apply to every cursor move, or just to hyperclicks / symbol navigation?

**Comment by hansonw** [comment]
Nuclide's navigation stack hooked into the `goToLocation` function to only apply to those moves, which was quite a bit better. We should be able to provide that as an Atom service.. let me do that, actually, so that you can hook into that.

**Comment by mehcode** [comment]
This sounds like a thing that is much better solved in a separate package. 

Here's my concept: 
 - Every _file activation_ should be added to the stack.
 - A _cursor move_ should update the current files "cursor" in the stack
 - A `_:go-back` command should move up the stack
 - A `_:go-forward` command should move down the stack
 - A new file activation would cause the stack to remove all items past the current stack index

That'd be a neat and medium difficulty package to make.

I do think that `atom-ide-ui` should provide this functionality (as its very common in IDEs). I just want it to be "all the way" and not just "return from declaration". It'd probably make more sense to have a separate package that is either inline like the rest of the packages or installed with atom-package-deps.

**Comment by matthewwithanm** [comment]
> We should be able to provide that as an Atom service.. let me do that, actually, so that you can hook into that.

Do we actually need a service you need to know about and use or can we just observe events?

**Comment by hansonw** [comment]
Where can we fire the events from? I guess it’d have to be somewhere that
other packages can access freely.

**Comment by matthewwithanm** [comment]
Oh I meant can we observe existing events. So instead of calling `gotoLocation()`, you'd just open an editor as normal and we'd notice it and add it to the stack.

**Comment by hansonw** [comment]
(Sorry for the inactivity here) I've thought a bit more about the 'navigation stack' feature recently and it does seem like there doesn't really have to be any special-casing for `goToLocation` -- tracking all cursor changes and active editor switches really does seem like the best general solution. It's helpful to also look at how VSCode implements its history functionality as a starting point: https://github.com/Microsoft/vscode/blob/ab1669f8987c585c260e824584e3bf79c82fc064/src/vs/workbench/services/history/electron-browser/history.ts#L104
