### ISSUE TITLE
Links to documentation for Feature Overview don't work

### ISSUE THREAD

**Issue by dinophile** [facebook-atom/atom-ide-ui#54]
### Description
In atom-ide-ui settings down at the bottom of the page none of the feature overview links do anything.

### Expected Behavior
They should lead to documentation for each feature?

### Actual Behavior
Nothing when you click on them...

### Versions
* Atom: 1.21.0-beta- x64
* Client OS: Kubuntu 16/04
* atom-ide-ui: 0.3.3

**Comment by hansonw** [comment]
Thanks, those links should be absolute. This'll work with the next release.
