### ISSUE TITLE
"Choose a linter UI" dialog doesn't dismiss if linter disabled manually

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#56]
### Description
If you have `linter` disabled and manually enable it, `atom-ide-ui` pops up a dialog asking to disable it or `atom-ide-diagnostics`. If the user then manually disables the `linter` package (**not** from the dialog), the dialog persists, still asking the user for a choice.

### Expected Behavior
Dialog should dismiss itself if the user disables `linter` manually.

This should be pretty simple, just add an [`onDidDeactivatePackage`](https://atom.io/docs/api/v1.20.1/PackageManager#instance-onDidDeactivatePackage) observer, and [`.dismiss()`](https://atom.io/docs/api/v1.20.1/Notification#instance-dismiss) the message if `linter` is disabled.

### Actual Behavior
Nothing happens.

### Versions
* Atom: v1.21.0-beta1
* Client OS: Windows 10 x64
* atom-ide-ui: 0.3.3

**Comment by hansonw** [comment]
Thanks! It's an even easier fix with observables 😄

**Comment by Arcanemagus** [comment]
Observing it was what I was suggesting already? Anyway, thanks for fixing it!

**Comment by hansonw** [comment]
Observable, as in rxjs.Observable (https://github.com/ReactiveX/rxjs)
