### ISSUE TITLE
Having Trouble Using the "Find References" Command.

### ISSUE THREAD

**Issue by SMLMRKHLMS** [facebook-atom/atom-ide-ui#57]
### Description
When I try to select Find > Find References after highlighting a variable I receive the following warning. 

<img width="516" alt="screen shot 2017-09-22 at 2 40 34 pm" src="https://user-images.githubusercontent.com/5240571/30759401-0df35aea-9fa4-11e7-878c-7b8f8f098a65.png">
I have followed up with trying to select Find References: Activate within the command palette and I am receiving the same warning. Am I missing a configuration step? How do I set up symbol references for a given project?

### Expected Behavior
Find References UI should become visible.

### Actual Behavior
I receive the aforementioned warning.

### Versions
* Atom: 1.20.1
* Client OS: macOS Sierra, Version 10.12.4
* atom-ide-ui: 0.3.3

**Comment by hansonw** [comment]
From the template: 

> ## Before Submitting
> 
> Have you installed an "ide-" language package? atom-ide-ui provides no functionality out-of-the box unless you've installed a suitable package.
> If your issue is language-specific, please file an issue against the "ide-" language package you're using instead.

Find References doesn't work automatically out of the box - you have to install a language package to power it :)
