### ISSUE TITLE
Segmentation fault in atom after installing atom-ide-ui

### ISSUE THREAD

**Issue by dchatterjee172** [facebook-atom/atom-ide-ui#59]
I have installed atom-ide-ui and ide-python
### Description
After opening a file through terminal like,
$ atom test.py 
Firstly it takes a lot of time to open, after a window opens, the window becomes unresponsive and i have to force close it, after force closing, this message comes in the terminal,
/usr/bin/atom: line 129:  3930 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

### Versions
* Atom: 1.20.1
* Client OS: Fedora 26
* atom-ide-ui: 0.4.0

**Comment by hansonw** [comment]
This seems unlikely to be an issue with the `atom-ide-ui` package. Are you sure it's directly correlated with `atom-ide-ui` being enabled: have you tried disabling/enabling it? You can also try `atom --clear-window-state` to see if it's just an issue with your currently serialized state.

**Comment by dchatterjee172** [comment]
@hansonw 
Yes I think it's directly correlated with atom-ide-ui package because when I disable this, I don't get any error, I have tried disabling and enabling it still the issue is same. Even with atom --clear-window-state the result is same, after opening , the window freezes.
https://imgur.com/a/oPaH7
https://imgur.com/a/1w57M
These are the screenshots.

**Comment by hansonw** [comment]
How about just atom-ide-ui, without ide-python? Also are you able to open
the developer tools console to see what's going on? You can also try going
to the Sources tab and hitting pause to see which code is hanging, maybe.

**Comment by dchatterjee172** [comment]
@hansonw 
Even after I disabled ide-python, it hanged badly
Please see this 
https://i.imgur.com/21sCBP7.png

**Comment by hansonw** [comment]
Hmm can you get a better quality screenshot? Also can you disable "pause on
uncaught exceptions" and use the regular pause/continue button; I dunno if
that exception is related.

**Comment by dchatterjee172** [comment]
@hansonw 
https://www.imageupload.co.uk/image/DNWw
https://www.imageupload.co.uk/image/DNWG
CPU usage is also getting very high
Okay I'll report using that...

**Comment by hansonw** [comment]
Yes just hit the button that looks like a play button while the CPU is high
so we can see where the stack is please :)

**Comment by dchatterjee172** [comment]
@hansonw 
here you go,
https://www.imageupload.co.uk/image/DNWI

**Comment by hansonw** [comment]
Ah, that helps. I wonder if something in your config file is off... can you
try moving your ~/.atom/config.cson somewhere else as a backup and then
restart Atom?

**Comment by dchatterjee172** [comment]
I removed that file, now it's not hanging that much,
one thing i noticed that if i disable ide-python it's not hanging that much after removing that file. I will test with another language and report

**Comment by dchatterjee172** [comment]
I have installed ide-c and ide-cpp package and tested with C code, and everything seems fine.. (Although it's not detecting any code errors, not even syntactical error).
@hansonw

**Comment by dchatterjee172** [comment]
after removing that file you said to remove,  I can confirm that this scenario is happening if ide-python and atom-ide-ui is enabled and i try to open a python file.
Should i restore that config file?
And what should I do next?
Should i create a issue in ide-python also?

**Comment by hansonw** [comment]
I dunno, it's hard to debug this remotely. After it's hung and you've
paused in the debugger, I'd try stepping through a bit to see if you can
figure out why it's hanging.

**Comment by dchatterjee172** [comment]
@hansonw 
It's staying in that same line

**Comment by hansonw** [comment]
Looks like you resolved this in https://github.com/lgeiger/ide-python/issues/18?
