### ISSUE TITLE
How to use the ui

### ISSUE THREAD

**Issue by neoxharsh** [facebook-atom/atom-ide-ui#60]
I have installed the atom-ide-ui and ide-typescript package, now when I open a javascript file, I still get the same old ui, nothing new. Am I doing something wrong?

**Comment by hansonw** [comment]
None of the interfaces are visible automatically; they have to be triggered. Please read over https://github.com/facebook-atom/atom-ide-ui#feature-overview to see how to use each of the features (I think typescript should support most of these, minus code actions, highlights, and formatting)
