### ISSUE TITLE
Preview syntax and ui from official page

### ISSUE THREAD

**Issue by visomi4** [facebook-atom/atom-ide-ui#63]
Hi!

I'm trying to change my UI and sintax themes in atom for looking like official atom-ide-ui preview video, but I dont know what its the correct package to make my atom look  [like this](https://ide.atom.io/).

Does any one know?

Thank you very much

**Comment by Arcanemagus** [comment]
It's an experimental theme from the author of the image based on One Dark / One Light that unfortunately isn't released yet. The author is currently on vacation from what I understand but there have been several requests for the theme to be published.

**Comment by visomi4** [comment]
@Arcanemagus thanks for response! I'm cant wait for the theme to be released :smile:

**Comment by karltaylor** [comment]
Do we know if he will release this theme? :)
