### ISSUE TITLE
Allow Status Bar to be positioned

### ISSUE THREAD

**Issue by johnmichel** [facebook-atom/atom-ide-ui#69]
Would be feasible to allow more customization with regards to placement of the icons in the Status Bar?  [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default) provided options for Left and Right that made the icons easier to see at a glance.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2V372R2H2o2Y142c1I32/%5Bf5f47665f6375cf92e02813a2a3932f6%5D_Screen%2520Shot%25202017-10-03%2520at%25209.41.09%2520AM.png)

**Comment by hansonw** [comment]
Great PR candidate! Just have to add a setting and consume it here: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/StatusBarTile.js#L85

**Comment by johnmichel** [comment]
@hansonw Thanks!  I created #84 to address this!
