### ISSUE TITLE
Does Nuclide Built-in Debugging get into Atom IDE ?

### ISSUE THREAD

**Issue by danielalmeidagoncalves** [facebook-atom/atom-ide-ui#75]
Would be great if Nuclide's Built-in Debugging would get into one of the next versions of Atom IDE, it this possible or is something it is not even in the roadmap?

**Comment by damieng** [comment]
Debugging is on the roadmap!

**Comment by nsrosenqvist** [comment]
Sorry to reply to a closed issue, just curious, is there an ETA for this and how would it be implemented? Would it be language agnostic and provide drivers for different languages/debuggers? I'd like to see some improvements to php-debug and I'm wondering if it's worth starting contributing to it or if we'll get a more "official" atom-backed solution in the future that we'd migrate to later anyway?

**Comment by hansonw** [comment]
@nsrosenqvist the most likely API for this would be the VS debug protocol (as an analog to the LSP, which is also from VSCode). This is the direction that we're taking for the Nuclide debugger, at least.

https://github.com/Microsoft/vscode-debugadapter-node

**Comment by nsrosenqvist** [comment]
@hansonw thanks! Didn't know there was a debugger equivalent, I'll start looking into it!

**Comment by lloiser** [comment]
I have noticed two commits ad369bfe01c2c28382e4cf2ebeff6c751f88c1cc and 67b0ecdbc6d88ca58b165aa8780057600e3a635a. Is this finally coming to atom-ide-ui? When is this planned to be published and how does a atom debugger plugin use it (documentation)? Can't wait for it 😁

**Comment by hansonw** [comment]
Yup @mostafaeweda is working on bringing this in. There will be more documentation about it once it stabilizes :P

**Comment by mostafaeweda** [comment]
It's coming!
More discussion will follow on #196
