### ISSUE TITLE
can't access nothing outline view 

### ISSUE THREAD

**Issue by mostafa6765** [facebook-atom/atom-ide-ui#76]
### Description
can't access outline view my laravel Illuminate\Foundation\Exceptions\Handler

### Actual Behavior
Atom ide can't access but alibaba package can access

### Versions
* Atom:1.22.0 beta 0
* Client OS: windows
* atom-ide-ui: 0.4.0

### Additional Details
![atom ide](https://user-images.githubusercontent.com/17185462/31282016-125cfcd2-aad3-11e7-8ada-8b83245ce961.png)

**Comment by damieng** [comment]
Have you installed ide-php ?

**Comment by mostafa6765** [comment]
yes , ide-php version is `0.6.9` . some files access by atom-ide but some can't access .

![ff](https://user-images.githubusercontent.com/17185462/31282929-d63a4112-aad5-11e7-979f-1d628485f181.PNG)

**Comment by damieng** [comment]
Can you open an issue over at ide-php - also if you can share a file that does not outline view please do as it will help us track down what's going wrong.

**Comment by mostafa6765** [comment]
Ok . [ide-php issue](https://github.com/atom/ide-php/issues/59)
