### ISSUE TITLE
Outline not working Hyperclick purpose . php!

### ISSUE THREAD

**Issue by mostafa6765** [facebook-atom/atom-ide-ui#77]
### Description
can't access outline view when hyperclick php

### Actual Behavior
Atom ide can't access but alibaba package can access

### Versions
* Atom:1.21.0
* Client OS: windows 10
* atom-ide-ui: 0.4.0

### Additional Details
![dd](https://user-images.githubusercontent.com/17185462/31307258-175a465e-ab82-11e7-9d06-4c691925aa20.PNG)

**Comment by damieng** [comment]
Is the ServiceProvider.php file inside the project?  Or is it elsewhere?

**Comment by mostafa6765** [comment]
yes , project inside . laravel framework parts

**Comment by damieng** [comment]
Right now language servers only analyze and provide services for the files contained in your project folder.

**Comment by hansonw** [comment]
Please file further PHP-related issues over at https://github.com/atom/ide-php. Thanks!
