### ISSUE TITLE
Outline view load but never show information

### ISSUE THREAD

**Issue by paulbonneau** [facebook-atom/atom-ide-ui#8]
I'm currently trying the atom-ide-ui package and having issue with outline view.
The panel where this view should give me information always show the loader but never display information about the current opened file in editor.

I tried it on a lot of different PHP files but still having the same issue.

Checked developper console but no error in it.

Atom version :
1.21.0-beta0
OS : 
Mac OSX Sierra 10.12.6

**Comment by hansonw** [comment]
Have you installed [ide-php](https://atom.io/packages/ide-php)? atom-ide-ui doesn't implement any language support on its own.

**Comment by paulbonneau** [comment]
Yes I installed it.

**Comment by hansonw** [comment]
I suspect this is more of a problem with the PHP language server. to confirm, can you 

1) Enable `core.debugLSP` (`atom.config.set('core.debugLSP', true)`) and reload Atom
2) Watch the console as you switch between files? There should be a `textDocument/documentSymbol` (Outline View uses that). Please verify that the response from the server looks reasonable.

**Comment by paulbonneau** [comment]
You're right, the problem came from my php version.
Weirdly, I made it work by switch back from 7.1 to 5.6 then switch to 7.1 again.

**Comment by damieng** [comment]
Hmm, that is weird. I wonder if 7.1 wasn't on the path - we try to detect that and display a helpful message.

If it happens again let us know - there might be something in the debug window that we can better detect.
