### ISSUE TITLE
Type column needs maximum (set?) width

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#83]
### Description
The `Type` column currently seems to take a percentage of the panel, but as this content should only be an indicator of severity it should only take the amount of space it _needs_, not the amount of space it could take up.

### Expected Behavior
![image](https://user-images.githubusercontent.com/427137/31398549-2ac85096-ad9e-11e7-98ab-085868aaedc7.png)

The column should only take the size it needs to, I've set it to `4 em` here, but I'm assuming there is a better way to do this as I am definitely _not_ a designer 😛.

### Actual Behavior
![image](https://user-images.githubusercontent.com/427137/31398466-e1a3a604-ad9d-11e7-8006-1c2e2e6c57eb.png)
The `Type` column is set to 5% of the panel size, which is too large, at least on a 1920x1080 monitor.

### Versions
* Atom: v1.22.0-beta0
* Client OS: Windows 10 x64
* atom-ide-ui: v0.5.0

**Comment by hansonw** [comment]
Fixed in 3beb6b97ac9af53eabaf6cb664542a52a0d3f7c2! I'll be patch-releasing this week.
