### ISSUE TITLE
Auto-hide diagnostics when nothing to show

### ISSUE THREAD

**Issue by mjomble** [facebook-atom/atom-ide-ui#88]
### Expected Behavior
It would be nice to have an option to automatically hide the diagnostics panel when there are no errors or warnings and to automatically show it when there are.
Or perhaps even make this the default behaviour.

### Actual Behavior
When there are no errors or warnings, the diagnostics panel stays open and takes up screen space that could be used for other things, but doesn't do anything useful.
If I manually hide the panel, it stays hidden even when errors or warnings do appear and then I need to manually re-open it to see them.

### Versions
* Atom: 1.21.0 x64
* Client OS: Windows 7
* atom-ide-ui: 0.5.1

**Comment by hansonw** [comment]
This will be under the "autoVisibility" setting in v0.5.2 (coming soon)
