### ISSUE TITLE
Support for Babel/Webpack aliases

### ISSUE THREAD

**Issue by SavePointSam** [facebook-atom/atom-ide-ui#9]
The doc for Definitions appears to show the ability to jump between files. When using custom aliases via Babel/Webpack, the tooltip just says alias and points to the import statement.

**Comment by hansonw** [comment]
Can you file this issue on the specific ide-* plugin that you're using (Sounds like typescript or flowtype)? atom-ide-ui is only responsible for the definitions infrastructure.
