### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by beriberikix** [facebook-atom/atom-ide-ui#91]
Please consider relicensing to MIT and removing the patent clause, like [React+friends](https://code.facebook.com/posts/1716776591680069/react-16-a-look-inside-an-api-compatible-rewrite-of-our-frontend-ui-library/) and [GraphQL](https://code.facebook.com/posts/121714468491809/relicensing-the-graphql-specification/). This would enable more companies and language communities to contribute to bringing IDE-like features to Atom.

**Comment by Goom11** [comment]
We're evaluating our open source projects' licenses, but each project is different and alternative licensing options will depend on a variety of factors.

**Comment by beriberikix** [comment]
Thank you for the update, @Goom11. The same reply was given in the React, which makes total sense. Since there isn't a decision yet, why not keep this issue open instead of closing (where it might get lost)?
