### ISSUE TITLE
Diagnostics seems to have no style

### ISSUE THREAD

**Issue by jpolo** [facebook-atom/atom-ide-ui#97]
![capture d ecran de 2017-10-18 19-31-06](https://user-images.githubusercontent.com/340789/31733157-18c48d30-b43b-11e7-8667-b1b428520b31.png)

### Description
Diagnostics panel seems to have no style. Hence is not usable.

### Versions
* Atom: 1.21.1
* Client OS: Ubuntu 17.04
* atom-ide-ui: 0.5.1

### Additional Details
* Installed packages (`apm ls --installed`):
atom-ide-ui@0.5.1
├── atom-import-sort@3.3.0 (disabled)
├── atom-mocha-snippets@0.6.3
├── autocomplete-json@5.5.0
├── busy-signal@1.4.3 (disabled)
├── docblockr@0.11.0
├── editorconfig@2.2.2
├── file-icons@2.1.13
├── ide-flowtype@0.17.4
├── ide-php@0.6.9
├── intentions@1.1.5 (disabled)
├── language-babel@2.75.2
├── language-elixir@0.20.3
├── language-reason@0.0.4
├── language-robot-framework@2.2.0
├── linter@2.2.0 (disabled)
├── linter-eslint@8.3.2
├── linter-jsonlint@1.3.0
├── linter-markdown@5.2.0
├── linter-pycodestyle@2.1.3
├── linter-sass-lint@1.8.3
├── linter-ui-default@1.6.10 (disabled)
├── minimap@4.29.7 (disabled)
├── nuclide@0.261.0 (disabled)
├── reason-refmt@0.3.2
└── sort-lines@0.18.0

**Comment by hansonw** [comment]
Does this persist when you restart Atom? Also can you open Atom's devtools (cmd-option-i) to check for any errors?

**Comment by jpolo** [comment]
It seems I had a atom process running somewhere in background that prevented from really restarting the editor...
